- README.md
- package.json
- rollup/main/default/classes/Rollup.cls
- rollup/main/default/classes/RollupTests.cls
- rollup/main/default/objects/Rollup__mdt/fields/FullRecalculationDefaultNumberValue__c.field-meta.xml
- rollup/main/default/objects/Rollup__mdt/fields/FullRecalculationDefaultStringValue__c.field-meta.xml
- rollup/main/default/objects/Rollup__mdt/validationRules/Only_one_override_can_be_set.validationRule-meta.xml
* Fixed invocable logic - no longer assumes all passed in records are of the same SObjectType / set of fields
* Added overrides to both CMDT and Invocable that allow for default values to be set for number-based and string-based rollup fields (including Datetime, Date, and Time-based fields)
* Added tests to ensure that override were working both from CMDT and invocable-based routes
> Flow improvements

- package.json
- rollup/main/default/classes/Rollup.cls
- rollup/main/default/classes/RollupTests.cls
* Fixed the test associated with a previously fixed bug to _actually_ prove the bug had been fixed - previously, if records fed into the Invocable action included formula fields with null values, `Rollup` would try to initialize the potentially pre-existing DB version of that record by writing to that formula field on the chance they were involved in the rollup calculation. Now, in addition to only re-querying for fields specific to the rollup operation, we also ensure if the field is null on the DB version of the record, it is only written to if the field is writeable.
* Removed the duplicate switch statements in `StringRollupCalculator` / `DecimalRollupCalculator`. In addition to making the indenting hellish, it was also slower. Used Chain of Responsibility at the parent class level to …
> V1.0.2 Chain Of Responsibility / further Flow improvements

- README.md
- package.json
- rollup/main/default/classes/Rollup.cls
- rollup/main/default/classes/RollupTests.cls
* Correctly initialize the "default" (database-version) instance of each calculation item passed in from an Invocable. (Fixes issue where if an item wasn't pre-existing, it would not get added to the comparison Map)
> v1.0.3 - last of the initial launch feedback

- config/project-scratch-def.json
- extra-tests/classes/RollupIntegrationTests.cls-meta.xml
- package.json
- rollup/main/default/classes/Rollup.cls
- rollup/main/default/classes/Rollup.cls-meta.xml
- rollup/main/default/classes/RollupEvaluator.cls
- rollup/main/default/classes/RollupEvaluator.cls-meta.xml
- rollup/main/default/classes/RollupEvaluatorTests.cls
- rollup/main/default/classes/RollupEvaluatorTests.cls-meta.xml
- rollup/main/default/classes/RollupFullBatchRecalculator.cls-meta.xml
- rollup/main/default/classes/RollupTests.cls
- rollup/main/default/classes/RollupTests.cls-meta.xml
- sfdx-project.json
Closes #7 - Added support for reparenting records, plus changes from @jamessimone for Spring '21 updates
> Added support for reparented records

- README.md
- package.json
- rollup/main/default/classes/Rollup.cls
- rollup/main/default/classes/RollupCalculator.cls
- rollup/main/default/classes/RollupCalculatorTests.cls
- rollup/main/default/classes/RollupTests.cls
- rollup/main/default/customMetadata/RollupControl.Org_Defaults.md-meta.xml
- rollup/main/default/layouts/RollupControl__mdt-Rollup Control Layout.layout-meta.xml
- rollup/main/default/objects/RollupControl__mdt/fields/MaxQueryRows__c.field-meta.xml
- rollup/main/default/objects/RollupControl__mdt/fields/MaximumRollupRetries__c.field-meta.xml
- rollup/main/default/profiles/Admin.profile-meta.xml
* Fix #35 by adding ALL ROWS support for Task/Event objects
* Improve scalability by examining current queries issued - add two fields on `RollupControl__mdt`, `MaxQueryRows__c` and `MaxRollupRetries__c` to aid in configuration related to this change
> Query Archived Records & Scalability Improvements

- README.md
- package.json
- rollup/main/default/classes/Rollup.cls
- rollup/main/default/classes/RollupTests.cls
* Fix for #49 by enabling truncation on update
* Fix for #48 by exposing `runFromApex(List<SObject> records, TriggerOperation rollupContext)` method - possible values for the `rollupContext` argument are: 
- TriggerOperation.AFTER_INSERT
- TriggerOperation.AFTER_UDATE
- TriggerOperation.BEFORE_DELETE
- TriggerOperation.AFTER_UNDELETE
> V1.1.7 - easier imperative Apex, fix truncation on update

- package.json
- rollup/core/classes/RollupCalculator.cls
- rollup/tests/RollupCalculatorTests.cls
- rollup/tests/RollupTests.cls
* Cleanup from #64 - moved added test over to `RollupCalculatorTests`
* Used codecov to guide adding additional test coverage
> V1.2.4 - Adding code coverage for RollupCalculatorTests

- package.json
- rollup/app/lwc/rollupForceRecalculation/__tests__/rollupForceRecalculation.test.js
- rollup/app/lwc/rollupForceRecalculation/rollupForceRecalculation.html
- rollup/core/classes/Rollup.cls
- rollup/core/classes/RollupEvaluator.cls
- rollup/core/classes/RollupRelationshipFieldFinder.cls
- rollup/tests/RollupRelationshipFieldFinderTests.cls
- rollup/tests/RollupTests.cls
- sfdx-project.json
* Fixes #74 by migrating away from the use of the Opportunity object in almost all of the `RollupTests` tests
* Fixes #69 by alternating between async contexts (when necessary), and not re-queueing / re-batching when already async unless necessary due to limits
> V1.2.7 - Better Async Processing & Test Updates

- README.md
- scripts/convert-dlrs-rules.apex
Closes #84 by adding an Apex script, `scripts/convert-dlrs-rules.apex` - this can be run as anonymous Apex in an org to convert all DLRS rules to Rollup rules.
Originally, I was going to make this an Apex class - but that would require both deploying the class, as well as deleting the class, before DLRS could be uninstalled, which seemed like additional work for admins/devs. Additionally, Salesforce does not provide great options for testing or mocking the deployment logic, so there's not really any benefits to having it as an Apex class - a script will be more convenient. I've tested this using several different types of DLRS rules to try to cover all of the differences in DLRS rules vs Rollup rules.
I also considered adding logic to deactivate the converted DLRS rules, but decided …
> Added Apex script to convert DLRS rules

- .github/workflows/deploy.yml
- .gitignore
- README.md
- extra-tests/classes/RollupIntegrationTests.cls
- package.json
- rollup/core/classes/Rollup.cls
- rollup/core/classes/RollupEvaluator.cls
- rollup/core/classes/RollupFullBatchRecalculator.cls
- rollup/core/classes/RollupShouldRunAsPicklist.cls
- rollup/core/classes/RollupShouldRunAsPicklist.cls-meta.xml
- rollup/core/customMetadata/RollupControl.Org_Defaults.md-meta.xml
- rollup/core/layouts/RollupControl__mdt-Rollup Control Layout.layout-meta.xml
- rollup/core/objects/RollupControl__mdt/fields/MaxNumberOfQueries__c.field-meta.xml
- rollup/core/profiles/Admin.profile-meta.xml
- rollup/tests/RollupEvaluatorTests.cls
- rollup/tests/RollupRelationshipFieldFinderTests.cls
- rollup/tests/RollupTests.cls
- scripts/build-and-promote-package.ps1
- sfdx-project.json
* Fixes #88 by automating build pipeline for package version creation, promotion, and replacement in README
* **BREAKING CHANGE** `RollupControl__mdt.MaxQueryRows__c` updated to `RollupControl__mdt.MaxNumberOfQueries__c` - this field was improperly named as part of [v1.1.2](https://github.com/jamessimone/apex-rollup/releases/tag/v1.1.2), to my chagrin. The concept for "Max Query Rows" was already encapsulated in `RollupControl__mdt.MaxLookupRowsBeforeBatching__c` field
* Fixed a bug reported by Katherine West where `RollupFullBatchRecalculator` would not properly reset field values when batching - this issue was exacerbated by the "Max Query Rows" updates, above; batching was happening way earlier than it should have because the limit that `Rollup` was looking to was 100 instead of 3000 …
> V1.2.15 - Automate build pipeline

- rollup/core/classes/Rollup.cls
- rollup/core/classes/RollupEvaluator.cls
- rollup/tests/RollupEvaluatorTests.cls
- rollup/tests/RollupTests.cls
- scripts/build-and-promote-package.ps1
- sfdx-project.json
* Additional cleanup spurred by having temporarily moved each Rollup's instance `eval` evaluator variable to be non-final, which in addition to being bothersome exposed some hand-off issues between the batch class version of Rollup and its queueable inner class. This also revealed a few spots where the `RollupControl__mdt` was being fetched twice for no reason.
* Introduced an explanatory comment on the `Database.executeBatch` section of Rollup's `runCalc` method, as a newcomer might find themselves ... wondering ... why we were re-initializing the class 😅🔍
* small heap size improvement in `RollupEvaluator` (cc @ssk42, in the event you had broken ground there, but this shouldn't be a merge-conflict scenario of any kind); holdover from #91; empty object pattern (`AlwaysTrueEvaluator`) …
> V1.2.16 - Slight performance tweaks

- scripts/convert-dlrs-rules.apex
We have some DLRS roll ups that were de-activated and didn't need to be migrated, this script adds a check for that
The deployment failed when the DLRS roll ups used on events and tasks were included, this code excludes those from migration.
> added more handling when migrating from DLRS

- README.md
- extra-tests/classes/RollupIntegrationTests.cls
- package.json
- rollup/core/classes/Rollup.cls
- rollup/core/classes/RollupEvaluator.cls
- rollup/core/classes/RollupRecursionItem.cls
- rollup/core/classes/RollupRecursionItem.cls-meta.xml
- rollup/tests/RollupCalculatorTests.cls
- rollup/tests/RollupRecursionItemTests.cls
- rollup/tests/RollupRecursionItemTests.cls-meta.xml
- rollup/tests/RollupTestUtils.cls
- rollup/tests/RollupTestUtils.cls-meta.xml
- rollup/tests/RollupTests.cls
- sfdx-project.json
* Added `RollupTestUtils.cls` to centralize mocking Id creation
* Added `RollupRecursionItem.cls` to properly encapsulate `equals()` and `hashCode()` implementation - big thanks again to @gdoenlen for contributing on this one
* Fixed an issue with the `deferredRollups` section that could lead to a gack when deferred rollups are being processed (thanks to Katherine West for reporting this one!)
> V1.2.18 - Correct hashCode implementation, deferred rollup bugfix

- README.md
- package.json
- rollup/core/classes/Rollup.cls
- rollup/core/classes/RollupCalculator.cls
- rollup/core/classes/RollupEvaluator.cls
- rollup/core/classes/RollupRelationshipFieldFinder.cls
- rollup/tests/RollupCalculatorTests.cls
- scripts/build-and-promote-package.ps1
- sfdx-project.json
* Fixes #102 by properly including calc item where clause fields in FIRST/LAST query fields
* Started caching RollupEvaluator.WhereFieldEvaluator for better performance, as there are now quite a few classes accessing it only in order to get the query fields
> v1.2.20 - FIRST/LAST bugfix for calc item where clause, better performance

- README.md
- package.json
- rollup/core/classes/Rollup.cls
- rollup/core/classes/RollupCalculator.cls
- rollup/core/classes/RollupEvaluator.cls
- rollup/core/classes/RollupFullBatchRecalculator.cls
- rollup/core/classes/RollupLogger.cls
- rollup/core/classes/RollupLogger.cls-meta.xml
- rollup/core/classes/RollupQueryBuilder.cls
- rollup/core/classes/RollupQueryBuilder.cls-meta.xml
- rollup/tests/RollupCalculatorTests.cls
- rollup/tests/RollupQueryBuilderTests.cls
- rollup/tests/RollupQueryBuilderTests.cls-meta.xml
- rollup/tests/RollupTests.cls
- sfdx-project.json
* Broke out logging to separate rollup object
* Broke out queries to separate builder (possible due to refactoring getParedFieldName out of querying methods in v1.2.23)
* Fixed an issue with COUNT rollups and string-based fields on reparenting
> v1.2.24 - COUNT reparenting bugfix & better separation of concerns

- README.md
- extra-tests/classes/RollupIntegrationTests.cls
- extra-tests/triggers/AccountTrigger.trigger
- extra-tests/triggers/AccountTrigger.trigger-meta.xml
- package.json
- rollup/core/classes/Rollup.cls
- rollup/core/classes/RollupCalculator.cls
- rollup/core/classes/RollupEvaluator.cls
- rollup/core/classes/RollupFullBatchRecalculator.cls
- rollup/core/classes/RollupQueryBuilder.cls
- rollup/core/classes/RollupRecursionItem.cls
- rollup/core/customMetadata/RollupControl.Org_Defaults.md-meta.xml
- rollup/core/layouts/RollupControl__mdt-Rollup Control Layout.layout-meta.xml
- rollup/core/objects/RollupControl__mdt/fields/IsMergeReparentingEnabled__c.field-meta.xml
- rollup/core/profiles/Admin.profile-meta.xml
- rollup/tests/RollupCalculatorTests.cls
- rollup/tests/RollupEvaluatorTests.cls
- rollup/tests/RollupRecursionItemTests.cls
- rollup/tests/RollupTests.cls
- sfdx-project.json
* Fixes #112 by adding configurable merge reparenting. This only affects Cases / Contacts / Accounts / Leads as these are the standard Salesforce objects where merging is supported. This also adds the requirement for `after delete` in Apex triggers; there is no corresponding equivalent for invocables since neither Flow nor PB support after delete operations (yet). Raised the visibility of the `Rollup.runFromApex` to global to assist with plugging the gap this leaves for people using flow-based rollups who also want to opt into the correct behavior for merge-based reparenting. This functionality is now gated behind the `RollupControl__mdt.IsMergeReparentingEnabled__c` checkbox field, which comes enabled by default on the `Org_Defaults` rollup control record. See the README section entitled …
> V1.2.25 - Merge reparenting & Recursion updates

- README.md
- extra-tests/classes/InvocableDrivenTests.cls
- package.json
- plugins/CustomObjectRollupLogger/README.md
- plugins/CustomObjectRollupLogger/classes/RollupCustomObjectLogger.cls
- plugins/CustomObjectRollupLogger/classes/RollupCustomObjectLoggerTests.cls
- plugins/CustomObjectRollupLogger/classes/RollupLogEventHandler.cls
- plugins/CustomObjectRollupLogger/layouts/RollupLog__c-Rollup Log Layout.layout-meta.xml
- plugins/CustomObjectRollupLogger/objects/RollupLog__c/RollupLog__c.object-meta.xml
- plugins/CustomObjectRollupLogger/objects/RollupLog__c/fields/ErrorWouldHaveBeenThrown__c.field-meta.xml
- plugins/CustomObjectRollupLogger/objects/RollupLog__c/fields/TransactionId__c.field-meta.xml
- plugins/CustomObjectRollupLogger/permissionsets/RollupLogViewer.permissionset-meta.xml
- plugins/CustomObjectRollupLogger/profiles/Admin.profile-meta.xml
- rollup/core/classes/Rollup.cls
- rollup/core/classes/RollupAsyncProcessor.cls
- rollup/core/classes/RollupFullBatchRecalculator.cls
- rollup/core/classes/RollupLogger.cls
- rollup/core/classes/RollupQueryBuilder.cls
- rollup/tests/RollupStandardIntegrationTests.cls
- rollup/tests/RollupTests.cls
- scripts/build-and-promote-package.ps1
- scripts/deploy-sfdx-project.json
- sfdx-project.json
* Fixes #146 by going further down the rollup orchestrator/conductor path - the 'outer' rollup (previously referred to as the batchRollup - deprecating that term so that it's clear when a rollup is batched versus queued versus run sync) now 'conducts' the inner rollups by storing the calcItems and oldCalcItems map. This should drastically reduce memory consumption by basically eliminating how many List<SObject> copies are being passed around in memory; whereas previously, the more CMDT/Rollup invocations you used, the more Lists were stored, now the outer rollup condenses that information into one place.
* Avoids a possible string overflow exception when using the Custom Rollup Logger
* Restores the packaging script to its former glory, including a more consistent update to the `README` …
> V1.2.38 - Rollup Goes On a Diet

- README.md
- config/data/CurrencyTypes.json
- config/project-scratch-def.json
- extra-tests/classes/InvocableDrivenTests.cls
- extra-tests/classes/RollupIntegrationTests.cls
- extra-tests/classes/RollupRelationshipFieldFinderTests.cls
- extra-tests/objects/Account/fields/MaxAmountRollupSummary__c.field-meta.xml
- extra-tests/objects/Account/fields/MinAmountRollupSummary__c.field-meta.xml
- extra-tests/objects/Account/fields/SumAmountRollupSummary__c.field-meta.xml
- extra-tests/objects/Account/fields/TotalAmountRollupSummary__c.field-meta.xml
- extra-tests/profiles/Admin.profile-meta.xml
- rollup/core/classes/RollupAsyncProcessor.cls
- rollup/core/classes/RollupCalculator.cls
- rollup/core/classes/RollupQueryBuilder.cls
- scripts/test.ps1
Closes #156 by adding support for multi-currency fields :dollar: :euro: :yen: 
- MIN, MAX, SUM, AVERAGE, FIRST and LAST operations now internally convert `calcItem` currency fields to the currency of the parent record so that the same currency is being used for any calculations
- Enabled multi-currency setting in `project-scratch-def.json` and added `CurrencyTypes.json` file for importing currencies - due to Salesforce limitations, currency type data can't be created in test classes, so they are loaded into the scratch org within the build pipeline
- Added platform roll-up summary fields on `Account` that are used in `RollupIntegrationTests` to ensure that `Rollup` calculations for multi-currency fields match the logic used by the platform
> Added multi-currency support

- README.md
- config/data/CurrencyTypes.json
- config/project-scratch-def.json
- extra-tests/classes/InvocableDrivenTests.cls
- extra-tests/classes/RollupEvaluatorTests.cls
- extra-tests/classes/RollupFlowBulkProcessorTests.cls
- extra-tests/classes/RollupFullRecalcTests.cls
- extra-tests/classes/RollupIntegrationTests.cls
- extra-tests/classes/RollupRelationshipFieldFinderTests.cls
- extra-tests/classes/RollupTestUtils.cls
- extra-tests/objects/Account/fields/MaxAmountRollupSummary__c.field-meta.xml
- extra-tests/objects/Account/fields/MinAmountRollupSummary__c.field-meta.xml
- extra-tests/objects/Account/fields/SumAmountRollupSummary__c.field-meta.xml
- extra-tests/objects/Account/fields/TotalAmountRollupSummary__c.field-meta.xml
- extra-tests/profiles/Admin.profile-meta.xml
- package.json
- rollup/core/classes/Rollup.cls
- rollup/core/classes/RollupAsyncProcessor.cls
- rollup/core/classes/RollupCalculator.cls
- rollup/core/classes/RollupCurrencyInfo.cls
- rollup/core/classes/RollupCurrencyInfo.cls-meta.xml
- rollup/core/classes/RollupDeferredFullRecalcProcessor.cls
- rollup/core/classes/RollupEvaluator.cls
- rollup/core/classes/RollupFlowBulkProcessor.cls
- rollup/core/classes/RollupFullBatchRecalculator.cls
- rollup/core/classes/RollupQueryBuilder.cls
- rollup/core/classes/RollupRelationshipFieldFinder.cls
- scripts/test.ps1
- sfdx-project.json
* @jongpie led the charge on fixing #156 by introducing basic multi-currency support - all orgs that don't make use of advanced currency management in conjunction with `DatedConversionRate` can now perform multi-currency rollups successfully (see the "Multi-Currency Orgs" section of the README for further info
* fixed #158 by properly referring to `FlowBulkProcessor` default properties
* fixed #159 by properly handling hierarchical rollups that don't make use of the Grandparent Relationship Field Path field
* fixed an issue in `RollupEvaluator` where if the value being evaluated had some text that matched its field name, part of the value could get stripped away - resulting in both false positives and false negatives!
* fixed #155 & #160 by tracking which parent-level fields have already …
> V1.2.43 - Multi-currency rollup support & bugfixes

- .github/workflows/deploy.yml
- extra-tests/classes/RollupIntegrationTests.cls
- package.json
- rollup/core/classes/Rollup.cls
- rollup/core/classes/RollupAsyncProcessor.cls
- scripts/build-and-promote-package.ps1
- sfdx-project.json
Doing some cleanup on the v1.3.0 release - 
* making the pipeline more resilient by hardening the `scripts/build-and-promote-package.ps1` ability to find the prior package version
* removing some duplication between `deploy.yml` and `package.json` npm scripts
* removed `this.syncRollups` property from `RollupAsyncProcessor` to cut down on heap size, made `runCalc` logic easier to follow
* Fix deferred rollup issue where a queueable with multiple targets turns into a batch job without regard for the batch job's lookup items not all matching the inner rollups lookup SObjectType (and field references, accordingly) - reported by Katherine West
> V1.3.1 - Heap Size Improvements, Deferred Rollup Bugfix

- README.md
- extra-tests/classes/RollupEvaluatorTests.cls
- extra-tests/classes/RollupTests.cls
- lint-staged.config.js
- package.json
- plugins/CustomObjectRollupLogger/README.md
- plugins/CustomObjectRollupLogger/objects/RollupLog__c/listViews/All.listView-meta.xml
- plugins/NebulaLogger/classes/RollupNebulaLoggerAdapter.cls
- plugins/NebulaLogger/tests/RollupNebulaLoggerAdapterTest.cls
- plugins/RollupCallback/classes/RollupDispatch.cls
- rollup/core/classes/RollupEvaluator.cls
- rollup/core/classes/RollupLogger.cls
- rollup/core/classes/RollupSObjectUpdater.cls
- scripts/build-and-promote-package.ps1
- sfdx-project.json
* some internal bookkeeping to reduce signal-to-noise ratio on PMD false-positives issued by `apex-assist` (the joys of working with dependent packages, some might say)
* Fixed pre-commit hook to properly work with `sfdx-scanner`
* Fixed #170 by stripping line breaks/tabs/carriage returns from evaluation messages
* Fixed #171 by properly handling the queried list of rollup loggers to combine when the first entry in the list is the included Apex Debug logger
* Fixes an issue reported by Katherine West where some where clauses with `in` ... within ... the value of a field were not being queried correctly
> V1.3.5 - Rollup Logging & Eval bugfixes

- .github/workflows/deploy.yml
- README.md
- extra-tests/classes/RollupFullRecalcTests.cls
- package.json
- plugins/CustomObjectRollupLogger/README.md
- plugins/CustomObjectRollupLogger/classes/RollupCustomObjectLogger.cls
- plugins/CustomObjectRollupLogger/classes/RollupLogBatchPurger.cls
- plugins/CustomObjectRollupLogger/classes/RollupPurgerSchedulable.cls
- plugins/CustomObjectRollupLogger/classes/RollupPurgerSchedulable.cls-meta.xml
- plugins/CustomObjectRollupLogger/profiles/Admin.profile-meta.xml
- plugins/CustomObjectRollupLogger/tests/RollupCustomObjectLoggerTests.cls
- plugins/CustomObjectRollupLogger/tests/RollupLogBatchPurgerTests.cls
- plugins/NebulaLogger/README.md
- plugins/NebulaLogger/classes/RollupNebulaLoggerAdapter.cls
- plugins/NebulaLogger/tests/RollupNebulaLoggerAdapterTest.cls
- rollup/app/lwc/rollupForceRecalculation/rollupForceRecalculation.html
- rollup/core/classes/Rollup.cls
- rollup/core/classes/RollupAsyncProcessor.cls
- rollup/core/classes/RollupCalculator.cls
- rollup/core/classes/RollupLogger.cls
- rollup/core/classes/RollupParentResetProcessor.cls
- rollup/core/classes/RollupQueryBuilder.cls
- rollup/core/classes/RollupSchedulable.cls
- rollup/core/classes/RollupSchedulable.cls-meta.xml
- rollup/core/profiles/Admin.profile-meta.xml
- sfdx-project.json
* Added helptext for singular (text-based) full recalc app screen so that users don't accidentally start their SOQL where clause (when applicable) with `WHERE`
* Further Winter '22 cleanup making use of the new `Enum.valueOf()` methods
* Upgraded Codecov plugin to v2 to avoid upcoming deprecation
* Fixed an issue reported by Katherine West where schedulable rollup classes wouldn't ... run
* Fixed an issue reported by Katherine West and jcart with some full recalculation code paths
> V1.3.8 - Schedulable Class Updates & Full Recalculation Adjustments

- README.md
- extra-tests/classes/CustomMetadataDrivenTests.cls
- extra-tests/classes/RollupCalculatorTests.cls
- extra-tests/classes/RollupEvaluatorTests.cls
- extra-tests/classes/RollupFullRecalcTests.cls
- extra-tests/classes/RollupIntegrationTests.cls
- extra-tests/classes/RollupTests.cls
- extra-tests/customMetadata/Rollup.ParentWhereClauseFromTrigger.md-meta.xml
- package.json
- rollup/core/classes/Rollup.cls
- rollup/core/classes/RollupAsyncProcessor.cls
- rollup/core/classes/RollupCalculator.cls
- rollup/core/classes/RollupEvaluator.cls
- rollup/core/classes/RollupFullBatchRecalculator.cls
- scripts/build-and-promote-package.ps1
- sfdx-project.json
* Fixes #207 by ensuring promotion script gets correct package Id to promote
* Adding missing fix for #203 - full recalc processors now respect lower Rollup Control batch size limits, too
* Patching a few issues further issues with CONCAT_DISTINCT, added in proper handling for old calc item matching and new one not matching for several operations
* Fixes #209 by deep cloning trigger records to prevent System.FinalException: Record is read-only
* Fix for #210 - properly reference cached calc items when performing full recalc across batches
* Fixes #204 by passing parent records through when parent-level filtering exists and the parent-level field referenced isn't on the current parent
> V1.3.11 - Full Recalc Improvements

- README.md
- extra-tests/classes/RollupTests.cls
- package.json
- rollup/core/classes/RollupAsyncProcessor.cls
- rollup/core/classes/RollupSObjectUpdater.cls
- sfdx-project.json
* Potential fix for #215 by deferring rollups where it wasn't possible to retrieve all additional calc items in one full recalculation
> v1.3.14 - Too Many Query Rows bugfix

- README.md
- extra-tests/classes/RollupCalculatorTests.cls
- extra-tests/classes/RollupFieldInitializerTests.cls
- package.json
- rollup/core/classes/RollupCalculator.cls
- rollup/core/classes/RollupFieldInitializer.cls
- sfdx-project.json
* permanently fixes #212 by correctly re-initializing decimal types (big thanks to the folks with the Apex team for helping me debug this issue)
* fixes a bug with COUNT_DISTINCT where null values could have been added to counts incorrectly while items were being deleted
> V1.3.15 - Permanent BigDecimal Fix & Bugfixes

- .gitignore
- README.md
- extra-tests/classes/RollupDateLiteralTests.cls
- extra-tests/classes/RollupEvaluatorTests.cls
- extra-tests/classes/RollupIntegrationTests.cls
- extra-tests/objects/Account/fields/NameFormula__c.field-meta.xml
- extra-tests/profiles/Admin.profile-meta.xml
- lint-staged.config.js
- package.json
- plugins/ExtraCodeCoverage/README.md
- rollup/core/classes/RollupCalculator.cls
- rollup/core/classes/RollupQueryBuilder.cls
- scripts/build-and-promote-package.ps1
- scripts/generateExtraCodeCoveragePlugin.ps1
- scripts/helper-functions.ps1
- sfdx-project.json
* Added [Code Coverage Plugin](https://github.com/jamessimone/apex-rollup/tree/v1.3.17/plugins/ExtraCodeCoverage) for orgs that need additional code coverage for rollup. This plugin is auto-updated whenever changes are made to qualifying tests found in the `extra-tests` directory (where "qualifying" means: "no reliance on custom fields, CMDT, flows, triggers, etc ...) - thanks to Karl Berlin for pointing out the need for this one 🚀
* Efficiency improvements within `RollupCalculator` by getting rid of intermediate lists/sets when possible prior to querying 🧮
* Fixed a broken test in `RollupDateLiteralTests` (didn't work for `NEXT_N_MONTHS` literal when the month in question was February and the test was always adding 30 days 🤦‍♂️)
> V1.3.17 - Code Coverage Plugin & Test Updates

- .github/workflows/deploy.yml
- README.md
- extra-tests/classes/RollupTests.cls
- package-lock.json
- package.json
- rollup/core/classes/Rollup.cls
- rollup/core/classes/RollupAsyncProcessor.cls
- rollup/core/classes/RollupCalculator.cls
- rollup/core/classes/RollupFinalizer.cls
- rollup/core/customMetadata/RollupControl.Org_Defaults.md-meta.xml
- rollup/core/layouts/RollupControl__mdt-Rollup Control Layout.layout-meta.xml
- rollup/core/objects/RollupControl__mdt/fields/ShouldRunSingleRecordsSynchronously__c.field-meta.xml
- rollup/core/profiles/Admin.profile-meta.xml
- sfdx-project.json
* Fixes #208 with a hybrid approach - adding `RollupControl__mdt.ShouldRunSingleRecordsSynchronously__c` to allow for better quality-of-life when it comes to single-record updates, and the addition of `FOR UPDATE` when querying parent-level records so that sequentially queued up single record updates (such as the ones introduced by using Lightning Data Service, a la [LWC Utils's SOQL Datatable](../../../tsalb/lwc-utils)
* (Hopefully) fixes #220 by introducing safe navigation into the reparenting logic within `RollupAsyncProcessor`
* Adds caching into the pipeline to speed things up
* Raises `LoggingLevel` for Queueable errors from `DEBUG` to `ERROR` in `RollupFinalizer`
Big thanks to @jongpie for reviewing the approach taken for #208 and the pipeline caching
> V1.3.18 - Support For Datatable-enqueued Rollups

- README.md
- package.json
- rollup/core/classes/RollupAsyncProcessor.cls
- sfdx-project.json
* Combating record lock issues generated by overnight scheduled rollup runs - `FOR UPDATE` was too aggressively locking the parent records in these cases
> v1.3.19 - Combating Record Lock Issues

- README.md
- extra-tests/classes/RollupDateLiteralTests.cls
- extra-tests/classes/RollupEvaluatorTests.cls
- extra-tests/classes/RollupFieldInitializerTests.cls
- extra-tests/classes/RollupFullRecalcTests.cls
- package.json
- rollup/core/classes/Rollup.cls
- rollup/core/classes/RollupAsyncProcessor.cls
- rollup/core/classes/RollupDateLiteral.cls
- rollup/core/classes/RollupEvaluator.cls
- rollup/core/classes/RollupFullBatchRecalculator.cls
- rollup/core/classes/RollupParentResetProcessor.cls
- sfdx-project.json
* Fixes #179 by ensuring `RollupParentResetProcessor` recalcs always run first when multiple operations are enqueued. Also added logging for when those parent-level fields are reset
* Added support for [date literal functions](https://developer.salesforce.com/docs/atlas.en-us.soql_sosl.meta/soql_sosl/sforce_api_calls_soql_select_date_functions.htm), started exploring any possible issues associated with #224
> V1.3.20 - Date Literal Function Support and RollupParentResetProcessor bugfix

- scripts/convert-dlrs-rules.apex
I had a couple errors when running the convert-dlrs-rules script, since DLRS uses the operator 'Avg' and Apex Rollups uses 'AVERAGE'.  I added a check where you're converting other operations to be compatible.  I don't think any tests exist for scripts so it's just this update.
> Adding check for 'Avg' operation

- README.md
- extra-tests/classes/CustomMetadataDrivenTests.cls
- extra-tests/classes/InvocableDrivenTests.cls
- extra-tests/classes/RollupCalculatorTests.cls
- extra-tests/classes/RollupFlowBulkProcessorTests.cls
- extra-tests/classes/RollupIntegrationTests.cls
- extra-tests/classes/RollupSObjectUpdaterTests.cls
- extra-tests/classes/RollupTests.cls
- package.json
- rollup/core/classes/Rollup.cls
- rollup/core/classes/RollupAsyncProcessor.cls
- rollup/core/classes/RollupCalcItemReplacer.cls
- rollup/core/classes/RollupCalculator.cls
- rollup/core/classes/RollupFlowBulkProcessor.cls
- rollup/core/classes/RollupLogger.cls
- rollup/core/classes/RollupSObjectUpdater.cls
- scripts/generatePackage.ps1
- sfdx-project.json
* (Tentatively) fixes #262 by implementing two CPU quality-of-life changes:
* Caching for `RollupCalculator`:
* **Old process**
- each parent item gets its own `RollupCalculator`
- each `RollupCalculator` is only used once 
* **New process**
- `RollupCalculator` gets initialized for first parent item
- subsequent parent items have their default values re-initialized; the same `RollupCalculator` is cached and re-used for each parent item for any given rollup operation
* Removed static variable in `RollupAsyncProcessor` that was causing downstream rollups to start in the same thread as an already-async rollup
* Fixes #265 by correctly passing through rollup order bys when called via `RollupFlowBulkProcessor`
* Fixes issue where not all rollups flagged to run sync would properly run in the …
> V1.4.5 - Performance Improvements

- README.md
- extra-tests/classes/RollupFullRecalcTests.cls
- extra-tests/classes/RollupIntegrationTests.cls
- package.json
- plugins/ExtraCodeCoverage/README.md
- rollup/app/lwc/recalculateParentRollupFlexipage/__tests__/recalculateParentRollupFlexipage.test.js
- rollup/app/lwc/recalculateParentRollupFlexipage/recalculateParentRollupFlexipage.js
- rollup/app/lwc/rollupForceRecalculation/__tests__/rollupForceRecalculation.test.js
- rollup/app/lwc/rollupForceRecalculation/rollupForceRecalculation.js
- rollup/core/classes/Rollup.cls
- rollup/core/classes/RollupAsyncProcessor.cls
- rollup/core/classes/RollupLogger.cls
- sfdx-project.json
* Fixes #176 (finally!!) by adding support for grandparent rollups from the singular full recalc button on (grand)parent records. Fixes an issue with full recalcs clearing values incorrectly on occasion.
* Bumps minor version to reflect some possible breaking changes discussed in #298
* Fixes an issue with some full recalc code paths where other parents' rollup values could get inadvertently cleared. The parent reset logic is now solely contained within code paths called from the full recalc application.
> v1.5.0 - Support Grandparent Rollups From Full Recalc Button

- README.md
- extra-tests/classes/RollupCalculatorTests.cls
- extra-tests/classes/RollupIntegrationTests.cls
- package.json
- rollup/app/lwc/recalculateParentRollupFlexipage/__tests__/recalculateParentRollupFlexipage.test.js
- rollup/app/lwc/rollupForceRecalculation/__tests__/rollupForceRecalculation.test.js
- rollup/app/lwc/rollupForceRecalculation/rollupForceRecalculation.js
- rollup/core/classes/Rollup.cls
- rollup/core/classes/RollupCalculator.cls
- rollup/core/classes/RollupLogger.cls
- sfdx-project.json
* Fixes #303 by properly handling potentially null dates on MIN/MAX operations
* Reduced code in Full Recalc app associated with retrieving `Rollup__mdt.RollupOperation__c` picklist values
> V1.5.1 - MIN/MAX on Date Fields Bugfix

- README.md
- extra-tests/classes/RollupCalculatorTests.cls
- extra-tests/classes/RollupIntegrationTests.cls
- package.json
- rollup/core/classes/Rollup.cls
- rollup/core/classes/RollupCalculator.cls
- rollup/core/classes/RollupLogger.cls
- rollup/core/classes/RollupRelationshipFieldFinder.cls
- sfdx-project.json
* Updated documentation in README, and added link to Wiki there
* Fixes #306 by preventing Ultimate Parent rollups from incorrectly querying the `UltimateParentLookup__c` before arriving at the parent-level object
* Fixes #307 by correctly passing subclasses of RollupCalculator.DecimalRollupCalculator the converted values for Date, Datetime, and Time instances
> V1.5.3 - One To Many rollup adjustments, MIN/MAX bugfixes

- README.md
- package.json
- rollup/core/classes/RollupEvaluator.cls
- rollup/core/classes/RollupLogger.cls
- rollup/core/classes/RollupPlugin.cls
- rollup/core/classes/RollupSObjectUpdater.cls
- sfdx-project.json
* Added support for dynamic handling of rollup updates by subscribers, as discussed in #297 - by default, RollupSObjectUpdater will simply call Database.update(recordsToUpdate, dmlOptions), but by using RollupPlugin__mdt and an entry with DeveloperName 'RollupSObjectUpdater', allow for things like bypassing trigger handlers on update - for more info, see the bullet point under the `Other Rollup Plugins` heading in the README
* Slight optimization in `RollupEvaluator`, with more to come there
> V1.5.4 - Customize How Parent-Level Records Are Updated

- README.md
- extra-tests/classes/RollupTests.cls
- package.json
- rollup/core/classes/RollupAsyncProcessor.cls
- rollup/core/classes/RollupCalculator.cls
- rollup/core/classes/RollupLogger.cls
- sfdx-project.json
* Fixed an issue where not all items were considered on update for `CONCAT_DISTINCT` if some of the items didn't match a Calc Item Where Clause
* Made _significant_ performance improvements to:
*  `CONCAT_DISTINCT` operations with more than one item
* Pretty much any rollup operation that includes more than one item where a Calc Item Where Clause is used (this is due to removing a duplicated call to `RollupEvaluator` - this was previously necessary to safeguard an obscure "order of operations" that applied when _standard_ Salesforce rollup fields that were in the middle of themselves being recalculated were used in a Calc Item Where Clause
> V1.5.5 - CONCAT_DISTINCT improvements

- README.md
- extra-tests/classes/RollupFlowBulkProcessorTests.cls
- extra-tests/classes/RollupFullRecalcTests.cls
- package.json
- rollup/core/classes/Rollup.cls
- rollup/core/classes/RollupAsyncProcessor.cls
- rollup/core/classes/RollupCalcItemReplacer.cls
- rollup/core/classes/RollupEvaluator.cls
- rollup/core/classes/RollupFlowBulkProcessor.cls
- rollup/core/classes/RollupFullRecalcProcessor.cls
- rollup/core/classes/RollupLogger.cls
- sfdx-project.json
* Did a little cleanup in Rollup.cls to break up the now quite large `performSerializedBulkFullRecalc` method while fixing a bug where invocations of that method internally (as opposed to from LWC) were sometimes resetting too many parent fields
* Fixed a bug reported by @rodgersjosh where full recalcs started through Flow when records were updated wouldn't properly perform the full recalculation for a Rollup Operation not already listed as a full recalc (bonus points if you made it through that sentence without your eyes crossing)
* Removed a now-unused method in RollupAsyncProcessor
> v1.5.11 - Full Recalc Tweaks

- README.md
- extra-tests/classes/RollupFullRecalcTests.cls
- package.json
- rollup/core/classes/RollupAsyncProcessor.cls
- rollup/core/classes/RollupFullRecalcProcessor.cls
- rollup/core/classes/RollupLogger.cls
- sfdx-project.json
* Rollups started from parent don't reset in-flight changed fields in the event that a parent record needs to have its values cleared. Previously, the version of the parent record used included all of the values from Flow/Apex when clearing a field which no longer had rollup values, but this meant that there was the possibility for changes made to the parent record while the rollup was processing to get those updates rolled back.
* Updated a few internal rollup method names to better account for what they were doing, and slightly optimized the batch job version of Apex Rollup
> V1.5.12 - Parent-based Rollups Fix

- README.md
- extra-tests/classes/RollupFlowBulkProcessorTests.cls
- extra-tests/classes/RollupFullRecalcTests.cls
- extra-tests/classes/RollupTests.cls
- package.json
- plugins/NebulaLogger/classes/RollupNebulaLoggerAdapter.cls
- plugins/NebulaLogger/tests/RollupNebulaLoggerAdapterTest.cls
- plugins/RollupCallback/classes/RollupDispatch.cls
- rollup/core/classes/Rollup.cls
- rollup/core/classes/RollupLogger.cls
- sfdx-project.json
* some slight cleanup of `@TestVisible` annotated variables
* full recalcs (kicked off via `REFRESH` context from flow, by rollups starting from the parent, or from the app) now should only update parent records if at least one rollup field had changed. Previously there was an edge case where parents whose rollup values were already null could also be included in full recalc updates, which had the downside of increasing the number of records being DML'ed - possibly leading to downstream CPU timeouts if there's a lot of other automation going on for the parent records. This should help alleviate that (to some extent, safe harbor 🚢)
> V1.5.16 - Avoid resetting parents when their fields are already blank

- README.md
- extra-tests/classes/RollupEvaluatorTests.cls
- extra-tests/classes/RollupFullRecalcTests.cls
- package.json
- rollup/core/classes/Rollup.cls
- rollup/core/classes/RollupEvaluator.cls
- rollup/core/classes/RollupLogger.cls
- sfdx-project.json
* fixes an issue reported by @solo-1234 where full recalcs with a large number of calc item where clauses could cause `RollupEvaluator` parsing errors during full recalcs
> V1.5.18 - Deeply Nested Conditional Bugfix

- README.md
- extra-tests/classes/RollupCalcItemReplacerTests.cls
- extra-tests/customMetadata/Rollup.RollupIntegrationChildRollupText.md-meta.xml
- extra-tests/customMetadata/RollupOrderBy.Integration_TextValue_FIRST.md-meta.xml
- package.json
- rollup/app/lwc/rollupForceRecalculation/__tests__/rollupForceRecalculation.test.js
- rollup/app/lwc/rollupForceRecalculation/rollupForceRecalculation.js
- rollup/core/classes/Rollup.cls
- rollup/core/classes/RollupCalcItemReplacer.cls
- rollup/core/classes/RollupLogger.cls
- sfdx-project.json
* [Further optimizations for full recalc rollup code paths by removing an intermediate inner class](https://github.com/jamessimone/apex-rollup/commit/53096b837275c63c19f2b951018190880b797621)
* [Fixes issue](https://github.com/jamessimone/apex-rollup/commit/f629816d4558e46ad8c6f3095b20bff63daa57cc)  reported by @solo-1234 where re-submitting a full recalc job for CMDT would improperly format the Rollup Order By CMDT records
* [Fixes issue](https://github.com/jamessimone/apex-rollup/commit/04a1c73cbcf06c66a20db128c753f2be6250ff01) reported by @solo-1234 where audit fields were causing RollupCalcItemReplacer to error out
> V1.5.24 - The Solo Admin Special

- README.md
- extra-tests/classes/InvocableDrivenTests.cls
- extra-tests/classes/RollupFullRecalcTests.cls
- extra-tests/classes/RollupTests.cls
- package.json
- plugins/RollupCallback/profiles/Admin.profile-meta.xml
- rollup-namespaced/README.md
- rollup-namespaced/sfdx-project.json
- rollup/app/lwc/__mockData__/index.js
- rollup/app/lwc/recalculateParentRollupFlexipage/__tests__/recalculateParentRollupFlexipage.test.js
- rollup/app/lwc/recalculateParentRollupFlexipage/recalculateParentRollupFlexipage.js
- rollup/app/lwc/rollupForceRecalculation/__tests__/rollupForceRecalculation.test.js
- rollup/app/lwc/rollupForceRecalculation/rollupForceRecalculation.html
- rollup/app/lwc/rollupForceRecalculation/rollupForceRecalculation.js
- rollup/app/lwc/rollupOrderBy/__tests__/rollupOrderBy.test.js
- rollup/app/lwc/rollupOrderBy/rollupOrderBy.js
- rollup/core/classes/Rollup.cls
- rollup/core/classes/RollupAsyncProcessor.cls
- rollup/core/classes/RollupFullBatchRecalculator.cls
- rollup/core/classes/RollupLimits.cls
- rollup/core/classes/RollupLimits.cls-meta.xml
- rollup/core/classes/RollupLogger.cls
- rollup/core/layouts/RollupControl__mdt-Rollup Control Layout.layout-meta.xml
- scripts/generatePackage.ps1
- scripts/test.ps1
- sfdx-project.json
* Further fixes for #376 to properly support parent items with massive numbers of children, including children counts in excess of the 50k per thread query row limit
* Adds `RollupLimit` class (pulling the same out of `Rollup`) to help with stubbing `System.Limit` calls when necessary
* QoL changes to full recalc app - spinner now doesn't lock down the "status" part of the page, and the job id is appended to the job status
> V1.5.30 - Proper deferrals for parents with 50k+ children

- README.md
- extra-tests/classes/RollupCalculatorTests.cls
- package.json
- rollup-namespaced/README.md
- rollup-namespaced/sfdx-project.json
- rollup/core/classes/RollupCalculator.cls
- rollup/core/classes/RollupDateLiteral.cls
- rollup/core/classes/RollupLogger.cls
- sfdx-project.json
* Added comprehensive support for rollup operations where, previously, if a Default Full Recalculation Value was supplied, it wasn't always used. As a reminder, `null` is the default value for parents without matching children (based on the same behavior that SOQL exhibits), but you can use `Rollup__mdt.FullRecalculationDefaultNumberValue__c` and `Rollup__mdt.FullRecalculationDefaultStringValue__c` to customize these values. All rollup operations now support those defaults.
* Fixed a few issues with rollup date literals - these have continued to persist, despite a comprehensive test suite for such things, because there are very subtle differences (sometimes on the order of a single second) in how date literals are calculated on the backend (with SOQL) and occasionally date math in Apex …
> V1.5.31 - More support for full recalculation default values

- README.md
- extra-tests/classes/RollupCalculatorTests.cls
- package.json
- rollup-namespaced/README.md
- rollup-namespaced/sfdx-project.json
- rollup/app/lwc/recalculateParentRollupFlexipage/__tests__/recalculateParentRollupFlexipage.test.js
- rollup/app/lwc/recalculateParentRollupFlexipage/recalculateParentRollupFlexipage.js
- rollup/app/lwc/rollupForceRecalculation/rollupForceRecalculation.html
- rollup/app/lwc/rollupForceRecalculation/rollupForceRecalculation.js
- rollup/app/lwc/rollupUtils/rollupUtils.js
- rollup/core/classes/Rollup.cls
- rollup/core/classes/RollupAsyncProcessor.cls
- rollup/core/classes/RollupCalculator.cls
- rollup/core/classes/RollupCurrencyInfo.cls
- rollup/core/classes/RollupFlowFullRecalcDispatcher.cls
- rollup/core/classes/RollupFullRecalcProcessor.cls
- rollup/core/classes/RollupLogger.cls
- sfdx-project.json
* fixes a bug reported by Stephen Stanley where the parent recalc button failed if Rollup Order Bys were defined
* trims even further down on heap size usage by clearing a stateful map being used by the batch full recalc processor - it's only necessary to maintain state until a parent record has finished being processed, at which point a ton of heap can be freed up by 
* removed a few unneeded enum values for operations like `MOST`, `ALL`, `NONE` and `SOME` since most code paths here follow the same logic
* now provide feedback faster when clicking the "Start Rollup!" button on the full recalc app. Thanks to @benblackthorn and @attilah for reporting this issue!
> v1.5.38 - Parent Recalc Button bugfix

- README.md
- extra-tests/classes/RollupFullRecalcTests.cls
- extra-tests/classes/RollupIntegrationTests.cls
- extra-tests/classes/RollupLoggerTests.cls
- extra-tests/classes/RollupTestUtils.cls
- extra-tests/classes/RollupTests.cls
- package.json
- rollup-namespaced/README.md
- rollup-namespaced/sfdx-project.json
- rollup/core/classes/Rollup.cls
- rollup/core/classes/RollupAsyncProcessor.cls
- rollup/core/classes/RollupCalcItemReplacer.cls
- rollup/core/classes/RollupEvaluator.cls
- rollup/core/classes/RollupFieldInitializer.cls
- rollup/core/classes/RollupFinalizer.cls
- rollup/core/classes/RollupFullBatchRecalculator.cls
- rollup/core/classes/RollupFullRecalcProcessor.cls
- rollup/core/classes/RollupLogger.cls
- rollup/core/classes/RollupParentResetProcessor.cls
- rollup/core/classes/RollupQueryBuilder.cls
- rollup/core/classes/RollupRelationshipFieldFinder.cls
- sfdx-project.json
* Fixes #363 by enabling logging for rollups controlled by something other than the Org Default RollupControl__mdt CMDT record for @solo-1234
* Updating SObjectDescribe calls where appropriate to use the SObjectDescribeOptions to fix new scan violations
> V1.5.40 - Enable Logging for Custom RollupControl__mdt records

- README.md
- package.json
- rollup-namespaced/README.md
- rollup-namespaced/sfdx-project.json
- rollup/core/classes/RollupAsyncProcessor.cls
- rollup/core/classes/RollupLogger.cls
- scripts/test.ps1
- sfdx-project.json
* Prevents `Database.executeBatch` call during full batch recalculations to avoid `Database.executeBatch cannot be called from a batch start, batch execute, or future method.`
> V1.5.41 - executeBatch Safety

- README.md
- extra-tests/classes/RollupSObjectUpdaterTests.cls
- package.json
- rollup-namespaced/README.md
- rollup-namespaced/sfdx-project.json
- rollup/core/classes/Rollup.cls
- rollup/core/classes/RollupAsyncProcessor.cls
- rollup/core/classes/RollupFullBatchRecalculator.cls
- rollup/core/classes/RollupLogger.cls
- rollup/core/classes/RollupPlugin.cls
- rollup/core/classes/RollupSObjectUpdater.cls
- sfdx-project.json
* Prevent too many queueables error by ensuring `RollupSObjectUpdater` does not split updates when in the midst of timing out
* Cleaned up some async code paths to continually refine CPU time usage
> V1.5.42 - Async Cleanup

- README.md
- extra-tests/classes/RollupParentResetProcessorTests.cls
- package.json
- rollup-namespaced/README.md
- rollup-namespaced/sfdx-project.json
- rollup/core/classes/Rollup.cls
- rollup/core/classes/RollupAsyncProcessor.cls
- rollup/core/classes/RollupFullBatchRecalculator.cls
- rollup/core/classes/RollupFullRecalcProcessor.cls
- rollup/core/classes/RollupLogger.cls
- rollup/core/classes/RollupParentResetProcessor.cls
- rollup/core/layouts/RollupControl__mdt-Rollup Control Layout.layout-meta.xml
- sfdx-project.json
* Updated logging levels to `INFO` for most high-level rollup operations. This allows `DEBUG` to be used to filter down to being able to answer the question "what did my parent-level records look like before/after rolling up?"
* Fixed an issue found while investigating #404 where the parent reset processor was occasionally running for full recalcs even when explicitly disabled via `RollupControl__mdt.ShouldSkipResettingParentFields__c`
> v1.5.44 - Updated most logging levels to INFO

- .gitignore
- README.md
- extra-tests/classes/RollupRepositoryTests.cls
- package.json
- rollup-namespaced/README.md
- rollup-namespaced/sfdx-project.json
- rollup/core/classes/Rollup.cls
- rollup/core/classes/RollupAsyncProcessor.cls
- rollup/core/classes/RollupCalcItemReplacer.cls
- rollup/core/classes/RollupCalculator.cls
- rollup/core/classes/RollupDateLiteral.cls
- rollup/core/classes/RollupDeferredFullRecalcProcessor.cls
- rollup/core/classes/RollupFullBatchRecalculator.cls
- rollup/core/classes/RollupFullRecalcProcessor.cls
- rollup/core/classes/RollupLogger.cls
- rollup/core/classes/RollupParentResetProcessor.cls
- rollup/core/classes/RollupRelationshipFieldFinder.cls
- rollup/core/classes/RollupRepository.cls
- sfdx-project.json
* Refactored `RollupRepository` allowing for less coupling between query bind variables and query locators (batch start) to run in user mode
* Promoted `RollupLogger` to global so that it can be overridden for consumers of the namespaced package
* Decorated logging messages in `RollupAsyncProcessor` which may help address an issue raised in #414 if it's not fixed by ...
* Tweaked `RollupAsyncProcessor.getAsyncRollup()` method to disallow fast-tracking full batch rollups if they're trying to restart from within a batch context (which would otherwise throw)
* Classic date literal updates to prevent cross-DST issues
> v1.5.54 - Further repository work, logging updates

- README.md
- config/project-scratch-def.json
- extra-tests/classes/RollupCalculatorTests.cls
- extra-tests/classes/RollupTests.cls
- package.json
- rollup-namespaced/README.md
- rollup-namespaced/sfdx-project.json
- rollup/core/classes/Rollup.cls
- rollup/core/classes/RollupAsyncProcessor.cls
- rollup/core/classes/RollupCalcItemReplacer.cls
- rollup/core/classes/RollupCalculator.cls
- rollup/core/classes/RollupCurrencyInfo.cls
- rollup/core/classes/RollupEvaluator.cls
- rollup/core/classes/RollupLimits.cls
- rollup/core/classes/RollupLogger.cls
- rollup/core/classes/RollupQueryBuilder.cls
- rollup/core/classes/RollupRepository.cls
- scripts/extra-metadata/Rollup.Opp_Eight.md-meta.xml
- scripts/extra-metadata/Rollup.Opp_Five.md-meta.xml
- scripts/extra-metadata/Rollup.Opp_Four.md-meta.xml
- scripts/extra-metadata/Rollup.Opp_Nine.md-meta.xml
- scripts/extra-metadata/Rollup.Opp_One.md-meta.xml
- scripts/extra-metadata/Rollup.Opp_Seven.md-meta.xml
- scripts/extra-metadata/Rollup.Opp_Six.md-meta.xml
- scripts/extra-metadata/Rollup.Opp_Three.md-meta.xml
- scripts/extra-metadata/Rollup.Opp_Two.md-meta.xml
- sfdx-project.json
* fixed a bug with ACM where a full recalc could fail for Opportunity-related items
* massive deep dive on CPU time for full recalcs with @jongpie and friends. This resulted in a number of optimizations for full recalcs, specifically:
* evaluating the result of where clauses - added some optimistic caching in here when parts of where clauses are shared between different rollups
* prevented an _extremely_ expensive `toString()` call that was being used even when rollup logging was disabled in `RollupEvaluator`
* added caching in a few other hot code spots related to full recalcs - particularly when mapping calc items to their corresponding parent keys
* prevented `RollupEvaluator` from being called in a full recalc if it was just going to be called later anyway. On a non-full recalc this …
> v1.5.56 - ACM bugfix, further optimizations

- README.md
- package.json
- rollup-namespaced/README.md
- rollup-namespaced/sfdx-project.json
- rollup/core/classes/RollupAsyncProcessor.cls
- rollup/core/classes/RollupLogger.cls
- rollup/core/classes/RollupRepository.cls
- sfdx-project.json
* Updates `RollupRepository.toString()` to be used properly in log messages
* Updated `RollupAsyncProcessor` to use the right record collection when resetting parent fields for full recalcs
> v1.5.58 - RollupRepository log message updates

- README.md
- extra-tests/classes/RollupCalcItemReplacerTests.cls
- extra-tests/classes/RollupEvaluatorTests.cls
- extra-tests/classes/RollupFlowBulkProcessorTests.cls
- extra-tests/classes/RollupFullRecalcTests.cls
- extra-tests/classes/RollupRelationshipFieldFinderTests.cls
- package.json
- rollup-namespaced/README.md
- rollup-namespaced/sfdx-project.json
- rollup/core/classes/Rollup.cls
- rollup/core/classes/RollupAsyncProcessor.cls
- rollup/core/classes/RollupCalcItemReplacer.cls
- rollup/core/classes/RollupEvaluator.cls
- rollup/core/classes/RollupFlowBulkProcessor.cls
- rollup/core/classes/RollupLogger.cls
- rollup/core/classes/RollupQueryBuilder.cls
- rollup/core/classes/RollupRelationshipFieldFinder.cls
- rollup/core/classes/RollupSObjectUpdater.cls
- sfdx-project.json
* Optimizes number of queries performed for full recalc grandparent rollups, which prevents the need to re-query the entire chain of objects between children and the parent records (since we already are starting with all children in a full recalc) care of #414 
* Optimizes `RollupFlowBulkProcessor` to consume less in the way of `Rollup__mdt` queries
* Optimizes `RollupCalcItemReplacer` to avoid calling some methods when there are no fields to replace
> v1.5.64 - Grandparent Rollup Optimizations

- README.md
- extra-tests/classes/RollupSObjectUpdaterTests.cls
- package.json
- rollup-namespaced/README.md
- rollup-namespaced/sfdx-project.json
- rollup/core/classes/RollupLogger.cls
- rollup/core/classes/RollupSObjectUpdater.cls
- rollup/core/customMetadata/RollupPlugin.RollupPreAndPostUpdater.md-meta.xml
- rollup/core/objects/RollupSettings__c/fields/BypassValidationRules__c.field-meta.xml
- sfdx-project.json
* Fixes #440 by including an internal, opt-in plugin, which updates .RollupSettings__c.BypassValidationRules__c so that validation rules can make exceptions for when Apex Rollup is the one updating records. For more info, see the `Rollup Plugins` section of the README - this (internally included) plugin allows subscribers to pre/post-process record synchronously, allowing for:
* additional updates to the `Database.DMLOptions` that Apex Rollup uses to be made pre-update
* any additional pre-processing _before_ parent records are updated can be made
* any additional post-processing that you would prefer to do synchronously on parent records can be made (I recommend using the Rollup Callback plugin to respond to updates in an asynchronous fashion, but it's always good to have options!). Keep …
> v1.5.65 - Support for Validation Rule Exclusions on Apex Rollup Updates

- README.md
- extra-tests/classes/RollupCalculatorTests.cls
- package.json
- rollup-namespaced/README.md
- rollup-namespaced/sfdx-project.json
- rollup/core/classes/Rollup.cls
- rollup/core/classes/RollupCalculator.cls
- rollup/core/classes/RollupLogger.cls
- sfdx-project.json
* Slight cleanup on some `RollupOrderBy__mdt` transformations
* Fixes an issue raised in #443 related to invalid casts being performed in `RollupCalculator`
> v1.5.66 - Small Cleanup

- README.md
- extra-tests/classes/RollupCalcItemReplacerTests.cls
- package.json
- rollup-namespaced/README.md
- rollup-namespaced/sfdx-project.json
- rollup/core/classes/RollupCalcItemReplacer.cls
- rollup/core/classes/RollupLogger.cls
- sfdx-project.json
* Removes chance for row with duplicate Id possibility in `RollupCalcItemReplacer`, reported by @fefris
> v1.5.68 - RollupCalcItemReplacer bugfix

- README.md
- extra-tests/classes/RollupLimitsTest.cls
- extra-tests/classes/RollupLimitsTest.cls-meta.xml
- extra-tests/classes/RollupTests.cls
- package.json
- rollup-namespaced/README.md
- rollup-namespaced/sfdx-project.json
- rollup/core/classes/RollupAsyncProcessor.cls
- rollup/core/classes/RollupLimits.cls
- rollup/core/classes/RollupLogger.cls
- sfdx-project.json
* Fixes #450 by adding guard check for daily org `AsyncApexJob` execution amount prior to going async
> v1.5.70 - AsyncApexJob Guard Clause

- README.md
- extra-tests/classes/RollupFlowBulkProcessorTests.cls
- extra-tests/classes/RollupFullRecalcTests.cls
- package.json
- rollup-namespaced/sfdx-project.json
- rollup/core/classes/Rollup.cls
- rollup/core/classes/RollupAsyncProcessor.cls
- rollup/core/classes/RollupFullRecalcProcessor.cls
- rollup/core/classes/RollupLogger.cls
- sfdx-project.json
* Fixes #459 by allowing rollups from different children types to be pointed to the same parent
> v1.5.74 - 2 Children Types Rolling Up To Same Parent Field

- README.md
- extra-tests/classes/RollupFullRecalcTests.cls
- package.json
- rollup-namespaced/sfdx-project.json
- rollup/core/classes/Rollup.cls
- rollup/core/classes/RollupAsyncProcessor.cls
- rollup/core/classes/RollupDateLiteral.cls
- rollup/core/classes/RollupEvaluator.cls
- rollup/core/classes/RollupLogger.cls
- rollup/core/classes/RollupParentResetProcessor.cls
- rollup/core/classes/RollupSObjectUpdater.cls
- sfdx-project.json
* Fixes an issue reported in #467 where parent values were not being reset properly between batches
* Fixes cascading update issue in full recalc app
* Prevents a number of extra queries being issued during full recalcs, which should speed them up _and_ prevent the full recalc app from exceeding the configured query limit (defaults to 50 queries as the max, currently)
* Small improvements made to `RollupParentResetProcessor` to prevent an unnecessary query from running
* Promoted `INFO` level logging statement back into `RollupSObjectUpdater`. Previously, this log message had been demoted to `FINEST` because it logged out all of the updated parent records; I've updated it to only log the number of parent records, which prevents it from overly contributing to heap size and is consistent …
> v1.5.77 - Two Batch Full Recalc Bugfixes

- README.md
- extra-tests/classes/RollupIntegrationTests.cls
- extra-tests/classes/RollupTests.cls
- package.json
- rollup-namespaced/sfdx-project.json
- rollup/core/classes/Rollup.cls
- rollup/core/classes/RollupAsyncProcessor.cls
- rollup/core/classes/RollupLimits.cls
- rollup/core/classes/RollupLogger.cls
- sfdx-project.json
* Fixes issue raised in #467 - proper null handling in RollupAsyncProcessor.retrieveAdditionalCalcItems when lookup field is null on calc items
* Optimized even further by preventing async run entirely when there was never a lookup field set
> v1.5.78 RollupAsyncProcessor.retrieveAdditionalCalcItems bugfix

- README.md
- extra-tests/classes/RollupTests.cls
- package.json
- rollup-namespaced/sfdx-project.json
- rollup/core/classes/RollupAsyncProcessor.cls
- rollup/core/classes/RollupLogger.cls
- scripts/convert-dlrs-rules-namespaced.apex
- scripts/deactivate-converted-dlrs-rules-namespaced.apex
- sfdx-project.json
* Prevent NPE for no-op property access in `RollupAsyncProcessor.getAsyncRollup`
* Fixes #474 by adding namespaced migration scripts for DLRS
> v1.5.79 - Fixes NPE In RollupAsyncProcessor

- README.md
- extra-tests/classes/RollupFullRecalcTests.cls
- package.json
- rollup-namespaced/README.md
- rollup-namespaced/sfdx-project.json
- rollup/core/classes/RollupAsyncProcessor.cls
- rollup/core/classes/RollupLogger.cls
- sfdx-project.json
* Heap reductions/optimizations with regards to how unexpected full recalcs (which populate rollup cabooses) store field-level data about parent/child query fields
> v1.5.82 - Rollup Caboose updates

- rollup/core/layouts/Rollup__mdt-Rollup Layout.layout-meta.xml
When entering the Label, the Name is automatically calculated, but if the name is cleared and the label edited, moving L-R means one less tab required.  Plus, this is in line with most Salesforce default focus paths that fill the name automatically on the first tab from the label.
> Change tab order for Rollup layout

- rollup/core/layouts/RollupControl__mdt-Rollup Control Layout.layout-meta.xml
- rollup/core/layouts/RollupOrderBy__mdt-Rollup Order By Layout.layout-meta.xml
- rollup/core/layouts/RollupPluginParameter__mdt-Rollup Plugin Parameter Layout.layout-meta.xml
- rollup/core/layouts/RollupPlugin__mdt-Rollup Plugin Layout.layout-meta.xml
Updating the rest of the CMDT layouts to match Salesforce recommendations to have `Name` tab immediately after `Label` to facilitate refreshing the name when label is changed (by clearing name and tabbing back and forth only once).
> refactor: All CMDT layouts top sections tab L-R

- README.md
- extra-tests/classes/RollupIntegrationTests.cls
- extra-tests/classes/RollupTests.cls
- package-lock.json
- package.json
- rollup-namespaced/README.md
- rollup-namespaced/sfdx-project.json
- rollup/core/classes/RollupCalculator.cls
- rollup/core/classes/RollupLogger.cls
- sfdx-project.json
* Fixes an issue reported by @windyo where count-based rollups going from one match to zero matches with a where clause on delete failed to decrement the parent value from 1 to 0
* Fixes #496 by properly handling case where additional calc items are the only matches during a count full recalc update
* Fixes `RollupIntegrationTests.limitsCorrectlyOnUpdate`, which used to occasionally flake and fail due to an implicit reliance on Id ordering
> v1.5.85 - COUNT bugfixes

- README.md
- extra-tests/classes/RollupDateLiteralTests.cls
- extra-tests/classes/RollupFullRecalcTests.cls
- extra-tests/classes/RollupIntegrationTests.cls
- extra-tests/classes/RollupParentResetProcessorTests.cls
- extra-tests/classes/RollupQueryBuilderTests.cls
- extra-tests/classes/RollupSObjectUpdaterTests.cls
- package.json
- rollup-namespaced/README.md
- rollup-namespaced/sfdx-project.json
- rollup/core/classes/RollupAsyncProcessor.cls
- rollup/core/classes/RollupDateLiteral.cls
- rollup/core/classes/RollupFullBatchRecalculator.cls
- rollup/core/classes/RollupFullRecalcProcessor.cls
- rollup/core/classes/RollupLogger.cls
- rollup/core/classes/RollupParentResetProcessor.cls
- rollup/core/classes/RollupQueryBuilder.cls
- rollup/core/classes/RollupSObjectUpdater.cls
- sfdx-project.json
* Fixes #494 by properly handling deeper-nested OR clauses in where clauses for rollups
* Fixes #500 by properly handling stateful maintenance of previously reset parents when children items cross multiple batches
* Made some notes on `WEEK_IN_YEAR` date literal to come back to
> v1.5.86 - OR clause bugfix and full recalc update

- README.md
- extra-tests/classes/RollupEvaluatorTests.cls
- extra-tests/classes/RollupFlowBulkProcessorTests.cls
- package.json
- rollup-namespaced/README.md
- rollup-namespaced/sfdx-project.json
- rollup/core/classes/Rollup.cls
- rollup/core/classes/RollupAsyncProcessor.cls
- rollup/core/classes/RollupDateLiteral.cls
- rollup/core/classes/RollupEvaluator.cls
- rollup/core/classes/RollupFullRecalcProcessor.cls
- rollup/core/classes/RollupLogger.cls
- rollup/core/classes/RollupRelationshipFieldFinder.cls
- rollup/core/classes/RollupSObjectUpdater.cls
- rollup/core/objects/Rollup__mdt/fields/IsFullRecordSet__c.field-meta.xml
- sfdx-project.json
* Fixes #514 by retrieving now-orphaned grandparent records when an intermediate lookup is changed and there are no further connections to the grandparent
* Fixing DST literals
* Adds additional logging to assist with #523
* Updating Is Full Record Set helptext
* Fixes #530 by detecting intermediate grandparent deletions
> v1.6.2 - Intermediate Grandparent Rollup bugfixes

- extra-tests/classes/RollupFlowTests.cls
- extra-tests/classes/RollupTests.cls
- package.json
- rollup-namespaced/sfdx-project.json
- rollup/core/classes/Rollup.cls
- rollup/core/classes/RollupFullRecalcProcessor.cls
- rollup/core/classes/RollupLogger.cls
- sfdx-project.json
* Added support for undelete in CDC triggers
* Updated expectations in a few CDC tests to more properly align with what actually happens in the `CREATE` and `GAP_CREATE` change types
* Fixed an issue with Flow where REFRESH flows that pass Parent Record Id For Empty Children Collections with the result of a non-matching Get Records input reported by Katherine West
> v1.6.7 - CDC updates

- README.md
- extra-tests/classes/RollupFlowBulkProcessorTests.cls
- extra-tests/classes/RollupParentResetProcessorTests.cls
- package.json
- rollup-namespaced/README.md
- rollup-namespaced/sfdx-project.json
- rollup/core/classes/Rollup.cls
- rollup/core/classes/RollupLogger.cls
- rollup/core/classes/RollupParentResetProcessor.cls
- sfdx-project.json
* Prevents `RollupParentResetProcessor` from attempting to reset fields on different parent objects
> v1.6.9 - Fixes "No such column 'Field__c' on entity 'Object' error"

- README.md
- extra-tests/classes/RollupFlowBulkProcessorTests.cls
- extra-tests/classes/RollupFullRecalcTests.cls
- package.json
- rollup-namespaced/README.md
- rollup-namespaced/sfdx-project.json
- rollup/core/classes/Rollup.cls
- rollup/core/classes/RollupAsyncProcessor.cls
- rollup/core/classes/RollupLogger.cls
- scripts/generatePackage.ps1
- sfdx-project.json
* Fixes an issue reported by @solo-1234 where rolling up 1 child to multiple parents where the parent types keep alternating lead to rollup fields accidentally being cleared
> v1.6.14 - Fixes ordering issue for batch full recalcs to multiple parents

- README.md
- extra-tests/classes/RollupFullRecalcTests.cls
- package-lock.json
- package.json
- rollup-namespaced/README.md
- rollup-namespaced/sfdx-project.json
- rollup/core/classes/Rollup.cls
- rollup/core/classes/RollupAsyncProcessor.cls
- rollup/core/classes/RollupEvaluator.cls
- rollup/core/classes/RollupLimits.cls
- rollup/core/classes/RollupLogger.cls
- rollup/core/classes/RollupParentResetProcessor.cls
- scripts/generatePackage.ps1
- sfdx-project.json
* continued optimization work for large batch full recalc operations, particularly those that roll up to multiple parent types from a single child type
* updated CLI version from 2.21.8 to 2.29.5
* skipped a version on the namespaced package so that it and the primary package are now in sync as far as version number goes
> v1.6.16 - Continued Optimizations

- README.md
- extra-tests/classes/RollupCalcItemReplacerTests.cls
- extra-tests/classes/RollupFlowBulkProcessorTests.cls
- extra-tests/classes/RollupFlowFullRecalcTests.cls
- extra-tests/classes/RollupFlowTests.cls
- extra-tests/classes/RollupFullRecalcTests.cls
- package.json
- rollup-namespaced/README.md
- rollup-namespaced/sfdx-project.json
- rollup/core/classes/Rollup.cls
- rollup/core/classes/RollupAsyncProcessor.cls
- rollup/core/classes/RollupCalcItemReplacer.cls
- rollup/core/classes/RollupFlowBulkProcessor.cls
- rollup/core/classes/RollupFullRecalcProcessor.cls
- rollup/core/classes/RollupLogger.cls
- sfdx-project.json
* Fixes an issue with where clauses beginning with `NOT(...)` in `RollupCalcItemReplacer`
* Several enhancements to REFRESH-based flows that help with recalculating rollups with multiple parents from the same child
* Flow performance enhancement - more rollups will now be prevented from going async when there are no matching calculations to perform
* Apex Rollup consumes count queries when determining whether queueable/batch is the appropriate "conductor" for going async based off of Rollup Control limits. This update improves the count-based logic to avoid double-counting children records whenever possible
> v1.6.18 - More accurate REFRESH calculations

- README.md
- extra-tests/classes/RollupIntegrationTests.cls
- package.json
- rollup-namespaced/README.md
- rollup-namespaced/sfdx-project.json
- rollup/core/classes/RollupAsyncProcessor.cls
- rollup/core/classes/RollupLogger.cls
- rollup/core/classes/RollupRelationshipFieldFinder.cls
- sfdx-project.json
* Fixes #581 by properly handling COUNT_DISTINCT for grandparent rollup deletions
> v1.6.22 - Grandparent COUNT_DISTINCT deletion bugfix

- README.md
- extra-tests/classes/RollupSObjectUpdaterTests.cls
- package.json
- rollup-namespaced/README.md
- rollup-namespaced/sfdx-project.json
- rollup/core/classes/RollupLogger.cls
- rollup/core/classes/RollupSObjectUpdater.cls
- rollup/core/customMetadata/RollupControl.Org_Defaults.md-meta.xml
- rollup/core/layouts/RollupControl__mdt-Rollup Control Layout.layout-meta.xml
- rollup/core/objects/RollupControl__mdt/fields/ShouldThrowOnSaveErrors__c.field-meta.xml
- sfdx-project.json
* Fixes an issue long-discussed in #523 that allows subscribers to throw errors on save with Apex Rollup instead of logging a WARN message
> v1.6.23 - Configurable Errors Thrown On Save

- .gitignore
- .vscode/settings.json
- README.md
- extra-tests/classes/RollupFullRecalcTests.cls
- extra-tests/classes/RollupRelationshipFieldFinderTests.cls
- extra-tests/classes/RollupTests.cls
- package.json
- rollup-namespaced/README.md
- rollup-namespaced/sfdx-project.json
- rollup/core/classes/RollupAsyncProcessor.cls
- rollup/core/classes/RollupLogger.cls
- rollup/core/classes/RollupParentResetProcessor.cls
- rollup/core/classes/RollupRelationshipFieldFinder.cls
- sfdx-project.json
* Fixed an issue with grandparent rollups where all parents couldn't be retrieved in one go due to polymorphic fields being used
* Fixes an issue reported by aesthetics where grandparent full recalc rollups with mutually exclusive where clauses could accidentally cache the previously filtered children from prior where clauses
> v1.6.29 - Grandparent rollup full recalc bugfixes

- README.md
- extra-tests/classes/RollupIntegrationTests.cls
- package.json
- rollup-namespaced/README.md
- rollup-namespaced/sfdx-project.json
- rollup/core/classes/Rollup.cls
- rollup/core/classes/RollupLogger.cls
- sfdx-project.json
Adds overload for `Rollup.runFromApex(List<SObject> children, Map<Id, SObject> oldChildrenMap, System.TriggerOperation rollupContext)` requested by @arbokrad
> v1.6.32 - Adds Rollup.runFromApex overload

- README.md
- extra-tests/classes/RollupDateLiteralTests.cls
- extra-tests/classes/RollupFullRecalcTests.cls
- package-lock.json
- package.json
- rollup-namespaced/README.md
- rollup-namespaced/sfdx-project.json
- rollup/core/classes/RollupAsyncProcessor.cls
- rollup/core/classes/RollupDateLiteral.cls
- rollup/core/classes/RollupLogger.cls
- sfdx-project.json
* Addresses issue reported on SFXD with `THIS_MONTH` date literal in APAC locales
* Investigating #616 with some full batch recalculation housekeeping
> v1.6.33 - THIS_MONTH date literal bugfix

- README.md
- extra-tests/classes/RollupCalcItemReplacerTests.cls
- package.json
- rollup-namespaced/README.md
- rollup-namespaced/sfdx-project.json
- rollup/core/classes/RollupCalcItemReplacer.cls
- rollup/core/classes/RollupDateLiteral.cls
- rollup/core/classes/RollupLogger.cls
- sfdx-project.json
* Fixes error reported interally with polymorphic where clause replacements being mutually exclusive with the current list of items
> v1.6.37 - RollupCalcItemReplacer bugfix

- .prettierrc
- README.md
- extra-tests/classes/RollupDateLiteralTests.cls
- extra-tests/classes/RollupIntegrationTests.cls
- package.json
- rollup-namespaced/README.md
- rollup-namespaced/sfdx-project.json
- rollup/core/classes/Rollup.cls
- rollup/core/classes/RollupDateLiteral.cls
- rollup/core/classes/RollupFullBatchRecalculator.cls
- rollup/core/classes/RollupFullRecalcProcessor.cls
- rollup/core/classes/RollupLogger.cls
- rollup/core/classes/RollupRepository.cls
- sfdx-project.json
* Fixes #640 by properly ensuring RollupDateLiteral comparisons occur in local time since they are always based off of the running user and their time zone
* Fixes an issue brought up in #639 where scheduling a rollup can inadvertently exceed the max query rows
> v1.7.1 - Scheduled Rollup Updates & Date literal comparisons

- README.md
- extra-tests/classes/RollupCalcItemReplacerTests.cls
- extra-tests/classes/RollupFlowBulkProcessorTests.cls
- package.json
- rollup-namespaced/README.md
- rollup-namespaced/sfdx-project.json
- rollup/core/classes/Rollup.cls
- rollup/core/classes/RollupCalcItemReplacer.cls
- rollup/core/classes/RollupLogger.cls
- sfdx-project.json
* Fixes issue reported with RollupCalcItemReplacer incorrectly detecting Type__r fields as polymorphic
> v1.7.2 - RollupCalcItemReplacer bugfix

- .github/workflows/deploy.yml
- README.md
- package.json
- rollup-namespaced/sfdx-project.json
- rollup/core/classes/RollupFieldInitializer.cls
- rollup/core/classes/RollupLogger.cls
- sfdx-project.json
* Fixes #643 by properly referencing Schema namespace in RollupFieldInitializer
> v1.7.3 - Fix Namespace Shadowing Issue

- README.md
- extra-tests/classes/RollupCalcItemReplacerTests.cls
- extra-tests/classes/RollupIntegrationTests.cls
- package.json
- rollup-namespaced/README.md
- rollup-namespaced/sfdx-project.json
- rollup/core/classes/RollupAsyncProcessor.cls
- rollup/core/classes/RollupCalcItemReplacer.cls
- rollup/core/classes/RollupFullBatchRecalculator.cls
- rollup/core/classes/RollupLogger.cls
- sfdx-project.json
* Fixes issue reported by internal colleague with RollupCalcItemReplacer when two rollups with parent-level fields use mutually exclusive where clauses on the same parent-level field
* Fixes #646 by providing escape hatch for cursor usage when batch apex is the originating point for Apex Rollup
> v1.7.4 - Allow Cursor Usage From Batch Apex

- README.md
- extra-tests/classes/RollupEvaluatorTests.cls
- extra-tests/classes/RollupTests.cls
- package.json
- rollup-namespaced/README.md
- rollup-namespaced/sfdx-project.json
- rollup/core/classes/RollupDateLiteral.cls
- rollup/core/classes/RollupEvaluator.cls
- rollup/core/classes/RollupLogger.cls
- rollup/core/classes/RollupState.cls
- sfdx-project.json
* Fixes #656 by adding better `INCLUDES` support in where clauses
* Updates `RollupDateLiteral` code path with suggestion from @surajp 
* Hard delete `RollupState__c` records at the end of bulk full recalcs thanks to community suggestions
> v1.7.6 - Better INCLUDES Support

- README.md
- extra-tests/classes/RollupCalcItemReplacerTests.cls
- extra-tests/objects/Account/fields/AType__c.field-meta.xml
- package.json
- rollup-namespaced/README.md
- rollup-namespaced/sfdx-project.json
- rollup/core/classes/RollupCalcItemReplacer.cls
- rollup/core/classes/RollupCurrencyInfo.cls
- rollup/core/classes/RollupLogger.cls
- sfdx-project.json
Fixes #660 by ensuring calls to split don't accidentally greedily split when detecting whether or not RollupCalcItemReplacer needs to run
> v1.7.8 - RollupCalcItemReplacer bugfix

- README.md
- extra-tests/classes/RollupFlowFullRecalcDispatcherTests.cls
- extra-tests/classes/RollupFullRecalcTests.cls
- extra-tests/classes/RollupIntegrationTests.cls
- package.json
- rollup-namespaced/sfdx-project.json
- rollup/core/classes/RollupFlowFullRecalcDispatcher.cls
- rollup/core/classes/RollupFlowRecalculator.cls
- rollup/core/classes/RollupFlowRecalculator.cls-meta.xml
- rollup/core/classes/RollupFullBatchRecalculator.cls
- rollup/core/classes/RollupLogger.cls
- rollup/core/classes/RollupRelationshipFieldFinder.cls
- sfdx-project.json
* Fixes an issue reported in #662 where the full recalc app would report a job as having completed before it actually had
* Additional field safety when selecting children records within `RollupRelationshipFieldFinder`
* Added new Flow full recalc code path for comma-separated list of parent API names
> v1.7.10 - RollupRelationshipFieldFinder bugfix

- README.md
- extra-tests/classes/RollupFullRecalcTests.cls
- package.json
- rollup-namespaced/README.md
- rollup-namespaced/sfdx-project.json
- rollup/core/classes/Rollup.cls
- rollup/core/classes/RollupAsyncProcessor.cls
- rollup/core/classes/RollupLogger.cls
- sfdx-project.json
* Fixes an issue discussed in #674 where Should Skip Resetting Parent Fields flag should also prevent default values from being applied during full recalcs
> v1.7.13 - Should Skip Resetting Parent Fields For Default Values

- README.md
- package.json
- rollup-namespaced/README.md
- rollup-namespaced/sfdx-project.json
- rollup/app/lwc/recalculateParentRollupFlexipage/recalculateParentRollupFlexipage.html
- rollup/app/lwc/recalculateParentRollupFlexipage/recalculateParentRollupFlexipage.js
- rollup/app/lwc/recalculateParentRollupQuickAction/recalculateParentRollupQuickAction.html
- rollup/app/lwc/rollupForceRecalculation/rollupForceRecalculation.html
- rollup/app/lwc/rollupForceRecalculation/rollupForceRecalculation.js
- rollup/app/lwc/rollupJobPoller/__tests__/rollupJobPoller.test.js
- rollup/app/lwc/rollupJobPoller/rollupJobPoller.html
- rollup/app/lwc/rollupJobPoller/rollupJobPoller.js
- rollup/app/lwc/rollupJobPoller/rollupJobPoller.js-meta.xml
- rollup/app/lwc/rollupUtils/__tests__/rollupUtils.test.js
- rollup/app/lwc/rollupUtils/rollupUtils.js
- rollup/core/classes/RollupLogger.cls
- rollup/core/classes/RollupParentResetProcessor.cls
- sfdx-project.json
* Fixes #686 by properly awaiting singular parent recalc buttons. _Most_ calculations occur synchronously, but if an async job is kicked off due to a large number of children records, the component(s) will still wait till the recalculation has completely finished
> v1.7.16 - Recalc Rollup Buttons Properly Wait

- README.md
- package.json
- rollup-namespaced/README.md
- rollup-namespaced/sfdx-project.json
- rollup/core/classes/RollupAsyncProcessor.cls
- rollup/core/classes/RollupLogger.cls
- sfdx-project.json
* Updates visibility modifier for `RollupAsyncProcessor.QueueableProcessor`, which in a regression to packaging unexpectedly broke ancestor version compatibility for some ISVs
> v1.7.25 - Fixes known issue with packaging first reported in #697
