- .gitignore
- README.md
- package.json
- rollup/main/default/classes/Rollup.cls
- rollup/main/default/classes/RollupTests.cls
- Fixes #6 by adding support for Change Data Capture
- Fixed bug with `TriggerOperation` not always being consistently set
- Fixes bug with use of custom fields as any of the four lookup fields in `Rollup__mdt`
> V1.0.4 - CDC Support & various bug fixes

- README.md
- rollup/main/default/classes/Rollup.cls
- rollup/main/default/classes/RollupFlowBulkProcessor.cls
- rollup/main/default/classes/RollupFlowBulkProcessor.cls-meta.xml
- rollup/main/default/classes/RollupFlowBulkProcessorTests.cls
- rollup/main/default/classes/RollupFlowBulkProcessorTests.cls-meta.xml
- rollup/main/default/classes/RollupFlowBulkSaver.cls
- rollup/main/default/classes/RollupFlowBulkSaver.cls-meta.xml
- scripts/test.ps1
- scripts/test.sh
* Fix #26 by adding new invocable to allow CMDT-driven flow rollups
* Fix #38 by adding deferred capabilities to both CMDT-driven and flow-driven rollups
> CMDT-driven rollups from flow & deferred flow rollups

- scripts/test.sh
Add bash version of `test.ps1`. It requires `jq` to be installed in addition to the Salesforce CLI
> Add test.sh for bash

- package.json
- rollup/main/default/classes/RollupCalculator.cls
- rollup/main/default/classes/RollupCalculatorTests.cls
- scripts/test.ps1
* Fixes #53 by ensuring string-based lookups conform to the multi-select picklist shape for concat in particular. cc @ssk42
> v1.1.9 - Multi-select picklist concat

- extra-tests/main/default/triggers/ApplicationTrigger.trigger
- extra-tests/main/default/triggers/ApplicationTrigger.trigger-meta.xml
- package.json
- rollup/main/default/classes/Rollup.cls
* added negative test via feedback from @JimBTek to ensure no further trigger-based regressions, fixed cached metadata issue
> v1.1.11 - Trigger/metadata bugfixes

- package.json
- rollup/core/classes/RollupCalculator.cls
- rollup/tests/RollupTests.cls
* Fixes #63 by correctly querying for Order By First Last field
> v1.2.3 - First / Last query bugfix

- rollup/core/classes/RollupEvaluator.cls
- rollup/tests/RollupEvaluatorTests.cls
* Removed some unused methods / extraneous functionality from `RollupEvaluator`
* Added tests for some evaluator code paths
> v1.2.4 patch: Adding additional code coverage for RollupEvaluator

- README.md
- package.json
- rollup/core/classes/Rollup.cls
- rollup/core/classes/RollupEvaluator.cls
- rollup/tests/RollupEvaluatorTests.cls
- rollup/tests/RollupTests.cls
- sfdx-project.json
* Fixes #72 by creating rollup package
* Fixes #71 by always correctly including query fields from Calc Item Where Clause
> V1.2.6 - Rollup Package Release

- README.md
- package.json
- scripts/convert-dlrs-rules.apex
I made a small change to the setup instructions to make it clear they are to be followed in order
I also added more details to the dlrs migration tool including adding debug output of rules that couldn't be migrated, aligned to the flow field names that they should apply to in order to make it easier to migrate remaining rules to flow actions.
PLEASE NOTE, i couldn't get prettier to work so the formatting is wrong
> Updates to migration tool

- README.md
- package.json
- rollup/core/classes/RollupCalculator.cls
- rollup/tests/RollupTests.cls
- sfdx-project.json
* Fix concat delimiter misplacement reported by Katherine West
> v1.2.22 - Concat bugfixes

- README.md
- extra-tests/classes/RollupIntegrationTests.cls
- package.json
- rollup/core/classes/Rollup.cls
- sfdx-project.json
* Update README typo - fix for downstream mergers
> v1.2.26 - Documentation updates, merge bugfix

- README.md
- package.json
- rollup/core/classes/RollupCalculator.cls
- rollup/tests/RollupCalculatorTests.cls
- sfdx-project.json
* Fixes issues reported by @solo-1234 where COUNT wasn't incrementing properly for "create or update" record-triggered flows
> Fix COUNT bug with UPSERT/UPDATE contexts

- README.md
- package.json
- rollup/core/classes/Rollup.cls
- rollup/core/classes/RollupCalculator.cls
- rollup/core/classes/RollupEvaluator.cls
- rollup/tests/RollupTests.cls
- sfdx-project.json
* Consolidate how query fields are filled within Rollup to fix FIRST/LAST issue
> v1.1.29 - FIRST/LAST bugfix

- README.md
- scripts/deactivate-converted-dlrs-rules.apex
Closes #134 by adding a 2nd script for DLRS - since not everyone will want to initially disable DLRS rules, it's safer to have this as a 2nd script.
> Added script to deactivate converted DLRS rules

- README.md
- package.json
- rollup/core/classes/Rollup.cls
- rollup/core/classes/RollupAsyncProcessor.cls
- rollup/tests/RollupStandardIntegrationTests.cls
- rollup/tests/RollupTestUtils.cls
- rollup/tests/RollupTests.cls
- sfdx-project.json
* Fixes #144 by adding reparenting recalc operation to new REFRESH context for flow invocables
* Added more rigorous tests for requeued operations and improved the logging for deferred rollups
> V1.2.37 - Added reparenting calculation to REFRESH

- .github/workflows/deploy.yml
- README.md
- package.json
- plugins/RollupCallback/README.md
- rollup/core/classes/RollupAsyncProcessor.cls
- sfdx-project.json
* Updating documentation - shuffled some README items around to hopefully improve setup/usage clarity. Also started linking to Wiki articles where possible
* Fix for #167 to prevent NPE in `runCalc() invocation`
> V1.3.3 - Doc Updates & Run Calc Bugfix

- README.md
- extra-tests/classes/RollupCalculatorTests.cls
- package.json
- rollup/core/classes/RollupCalculator.cls
- sfdx-project.json
* Fixing CONCAT_DISTINCT + SplitConcatDelimiter__c bug thanks to Katherine West
> v.1.3.16 - Fixing CONCAT_DISTINCT + SplitConcatDelimiter__c bug

- README.md
- package.json
- rollup/core/classes/RollupLogger.cls
- rollup/core/classes/RollupRecursionItem.cls
- sfdx-project.json
* Updating `hashCode` implementation to properly override for `RollupRecursionItem`
> v1.4.3 - Updating hashCode implementation

- README.md
- extra-tests/classes/RollupDateLiteralTests.cls
- extra-tests/classes/RollupEvaluatorTests.cls
- package.json
- rollup/core/classes/RollupAsyncProcessor.cls
- rollup/core/classes/RollupCalculator.cls
- rollup/core/classes/RollupDateLiteral.cls
- rollup/core/classes/RollupLogger.cls
- rollup/core/classes/RollupParentResetProcessor.cls
- sfdx-project.json
* Fixes #292 by correctly adding support for N_X_AGO date literals
* Explicit usage of without sharing everywhere
> V1.4.12 - Added support for N_X_AGO SOQL Date Literals

- README.md
- extra-tests/classes/RollupEvaluatorTests.cls
- package.json
- rollup/core/classes/RollupEvaluator.cls
- rollup/core/classes/RollupLogger.cls
- sfdx-project.json
* Removing case sensitivity when comparing strings in `RollupEvaluator` as per our discussion in #302
> v1.5.2 Removing case sensitivity in RollupEvaluator

- README.md
- extra-tests/classes/RollupFullRecalcTests.cls
- extra-tests/classes/RollupQueryBuilderTests.cls
- package.json
- rollup/core/classes/Rollup.cls
- rollup/core/classes/RollupCurrencyInfo.cls
- rollup/core/classes/RollupLogger.cls
- rollup/core/classes/RollupQueryBuilder.cls
- rollup/core/customMetadata/RollupControl.Org_Defaults.md-meta.xml
- scripts/test.sh
- sfdx-project.json
* Always add `CurrencyIsoCode` to queries for multi-currency orgs to fix #329
> v1.5.14 - Multi-currency Rollup Bugfix

- README.md
- extra-tests/classes/RollupFullRecalcTests.cls
- package.json
- rollup/core/classes/Rollup.cls
- rollup/core/classes/RollupFullRecalcProcessor.cls
- rollup/core/classes/RollupLogger.cls
- sfdx-project.json
* Worked with @solo-1234 to fix an issue introduced in #347 where full recalc rollups created by REFRESH flows didn't always get initialized with the correct SOQL query syntax
> v1.5.15 - Fixes REFRESH query issue from v1.5.14

- README.md
- extra-tests/classes/RollupFullRecalcTests.cls
- package.json
- rollup/core/classes/Rollup.cls
- rollup/core/classes/RollupAsyncProcessor.cls
- rollup/core/classes/RollupCalculator.cls
- rollup/core/classes/RollupLogger.cls
- rollup/core/classes/RollupRelationshipFieldFinder.cls
- sfdx-project.json
* Fixes #350 by ensuring parent records get retrieved as part of bulk full recalcs (which prevents the parent reset processor from updating values from null to null unnecessarily
* Optimized a few of the code paths related to multi-currency while debugging #329
> v1.5.17 - Multi-Currency Improvements & Bugfixes

- .gitignore
- README.md
- extra-tests/classes/RollupCurrencyInfoTests.cls
- package.json
- rollup-namespaced/README.md
- rollup-namespaced/sfdx-project.json
- rollup/core/classes/Rollup.cls
- rollup/core/classes/RollupCalcItemReplacer.cls
- rollup/core/classes/RollupCurrencyInfo.cls
- rollup/core/classes/RollupLogger.cls
- scripts/generatePackage.ps1
- sfdx-project.json
* Fixes an issue reported by @kd280z where multicurrency rollups can fail if the child item rollup field is a currency formula field
> V1.5.22 - Multicurrency Formula Field Conversion

- README.md
- extra-tests/classes/RollupFullRecalcTests.cls
- package.json
- rollup-namespaced/sfdx-project.json
- rollup/core/classes/Rollup.cls
- rollup/core/classes/RollupLogger.cls
- rollup/core/classes/RollupParentResetProcessor.cls
- rollup/core/classes/RollupSObjectUpdater.cls
- rollup/core/profiles/Admin.profile-meta.xml
- scripts/generatePackage.ps1
- sfdx-project.json
* Fixes issue reported by @solo-1234 where sometimes a bulk full recalc through the parent reset button or app would improperly reset some parent-level fields
> V1.5.23 - Parent Reset Processor fix

- README.md
- extra-tests/classes/RollupTests.cls
- package.json
- rollup-namespaced/README.md
- rollup-namespaced/sfdx-project.json
- rollup/core/classes/RollupCalculator.cls
- rollup/core/classes/RollupDateLiteral.cls
- rollup/core/classes/RollupLogger.cls
- sfdx-project.json
* Fixes an issue with COUNT-based calculations that also employ `Rollup__mdt.IsFullRecordSet__c`
* Corrects ending bound for the `THIS_WEEK` date literal
> v1.5.33 - COUNT-based bugfix for IsFullRecordSet__c calculations

- README.md
- extra-tests/classes/RollupFullRecalcTests.cls
- package.json
- plugins/NebulaLogger/README.md
- plugins/NebulaLogger/tests/RollupNebulaLoggerAdapterTest.cls
- rollup-namespaced/README.md
- rollup-namespaced/sfdx-project.json
- rollup/core/classes/Rollup.cls
- rollup/core/classes/RollupAsyncProcessor.cls
- rollup/core/classes/RollupDeferredFullRecalcProcessor.cls
- rollup/core/classes/RollupFullBatchRecalculator.cls
- rollup/core/classes/RollupFullRecalcProcessor.cls
- rollup/core/classes/RollupLogger.cls
- sfdx-project.json
* continuing on full recalc improvements by reducing heap usage for full recalc processors
* Updated RollupNebulaLoggerPlugin to simplify testing - and make the test more resilient to some updates in Nebula
> v1.5.36 - Further Heap Reductions

- .github/workflows/deploy.yml
- README.md
- extra-tests/classes/RollupCurrencyInfoTests.cls
- package.json
- rollup-namespaced/README.md
- rollup-namespaced/sfdx-project.json
- rollup/core/classes/RollupAsyncProcessor.cls
- rollup/core/classes/RollupCalculator.cls
- rollup/core/classes/RollupCurrencyInfo.cls
- rollup/core/classes/RollupLogger.cls
- scripts/generatePackage.ps1
- scripts/integration-test-large-data-volume.ps1
- scripts/record-creation-one-parent-many-children.apex
- scripts/start-and-return-batch-status.apex
- scripts/string-utils.ps1
- scripts/test.ps1
- sfdx-project.json
* Created integration testing framework that allows for arbitrary "call and response" polling to take place between Apex scripts, enabling the addition of integration test with 80k opportunities getting rolled up
* Added support for dated conversion rates with advanced currency management
> V1.5.37 - Dated Conversion Rate Support

- README.md
- extra-tests/classes/RollupCalculatorTests.cls
- extra-tests/classes/RollupSObjectUpdaterTests.cls
- package.json
- rollup-namespaced/README.md
- rollup-namespaced/sfdx-project.json
- rollup/core/classes/RollupCalculator.cls
- rollup/core/classes/RollupLogger.cls
- rollup/core/classes/RollupSObjectUpdater.cls
- sfdx-project.json
* Adds support for rolling up text fields that have date/datetime values in them
> V1.5.43 - Parsing Text-based Date/Datetime Support

- README.md
- extra-tests/classes/RollupFullRecalcTests.cls
- extra-tests/classes/RollupRelationshipFieldFinderTests.cls
- extra-tests/classes/RollupRepositoryTests.cls
- extra-tests/classes/RollupRepositoryTests.cls-meta.xml
- package.json
- rollup-namespaced/README.md
- rollup-namespaced/sfdx-project.json
- rollup/core/classes/Rollup.cls
- rollup/core/classes/RollupAsyncProcessor.cls
- rollup/core/classes/RollupCalcItemReplacer.cls
- rollup/core/classes/RollupCalculator.cls
- rollup/core/classes/RollupFullRecalcProcessor.cls
- rollup/core/classes/RollupLogger.cls
- rollup/core/classes/RollupQueryBuilder.cls
- rollup/core/classes/RollupRelationshipFieldFinder.cls
- rollup/core/classes/RollupRepository.cls
- sfdx-project.json
* Fixes #411 by properly retrieving grandparent-adjacent children for rollups where all records are required in order to properly perform calculations
* Continued Spring 23 consolidation of variables
> v1.5.49 - Continued Spring 23 consolidation, bugfix

- README.md
- extra-tests/classes/RollupCalculatorTests.cls
- package.json
- rollup-namespaced/README.md
- rollup-namespaced/sfdx-project.json
- rollup/core/classes/RollupCalculator.cls
- rollup/core/classes/RollupCurrencyInfo.cls
- rollup/core/classes/RollupFullBatchRecalculator.cls
- rollup/core/classes/RollupLogger.cls
- sfdx-project.json
* Removed a crazy hack for identifying rich text fields in favor of an actual Describe call thanks to @jongpie 
* Fixes #415 by properly transforming the old version of children for update scenarios
* Added guard clause for `System.isBatch()` in `RollupFullBatchRecalculator` which should address an issue brought up in #414
> V1.5.51 - Multi-currency Bugfix

- README.md
- rollup-namespaced/README.md
- rollup-namespaced/sfdx-project.json
- rollup/core/classes/RollupAsyncProcessor.cls
- sfdx-project.json
* Recommitting `RollupAsyncProcessor` change that was missed
> v1.5.54 - Update

- README.md
- extra-tests/classes/RollupRepositoryTests.cls
- extra-tests/classes/RollupTests.cls
- package.json
- rollup-namespaced/README.md
- rollup-namespaced/sfdx-project.json
- rollup/core/classes/Rollup.cls
- rollup/core/classes/RollupAsyncProcessor.cls
- rollup/core/classes/RollupDateLiteral.cls
- rollup/core/classes/RollupFullBatchRecalculator.cls
- rollup/core/classes/RollupFullRecalcProcessor.cls
- rollup/core/classes/RollupLogger.cls
- rollup/core/classes/RollupMetaPicklists.cls
- rollup/core/classes/RollupParentResetProcessor.cls
- rollup/core/classes/RollupQueryBuilder.cls
- rollup/core/classes/RollupRepository.cls
- sfdx-project.json
* Updates to avoid serialization issues with `System.AccessLevel`
* Further optimizations: 
* updates to `RollupMetaPicklists` to avoid excessive validation calls
* updated a few regexes to avoid undue CPU time
* less reliance on `System` calls that can be expensive
> v1.5.60 - System.AccessLevel updates

- README.md
- package.json
- rollup-namespaced/README.md
- rollup-namespaced/sfdx-project.json
- rollup/core/classes/Rollup.cls
- rollup/core/classes/RollupAsyncProcessor.cls
- rollup/core/classes/RollupFullBatchRecalculator.cls
- rollup/core/classes/RollupFullRecalcProcessor.cls
- rollup/core/classes/RollupLogger.cls
- sfdx-project.json
* Vastly simplified `Rollup.toString`, avoiding unncessary heap consumption when logging is disabled
> v1.5.61 - Further Heap Reductions

- README.md
- extra-tests/classes/InvocableDrivenTests.cls
- package.json
- rollup-namespaced/sfdx-project.json
- rollup/core/classes/RollupCalculator.cls
- rollup/core/classes/RollupLogger.cls
- sfdx-project.json
* Fixes an issue reported in #457 where using a Limit Amount in conjunction with first/last can throw an error if the number of children exceeds the limit amount
> v1.5.73 - Limit Amount bugfix

- README.md
- extra-tests/classes/RollupRelationshipFieldFinderTests.cls
- package.json
- rollup-namespaced/sfdx-project.json
- rollup/core/classes/RollupAsyncProcessor.cls
- rollup/core/classes/RollupLogger.cls
- rollup/core/classes/RollupRelationshipFieldFinder.cls
- sfdx-project.json
* fix for one-to-many grandparent rollups not always retrieving descendant children for full recalc-based rollups
> v1.5.75 - One-To-Many Grandparent Bugfix

- README.md
- extra-tests/classes/InvocableDrivenTests.cls
- extra-tests/classes/RollupCalcItemReplacerTests.cls
- extra-tests/classes/RollupFullRecalcTests.cls
- extra-tests/flows/Rollup_Integration_refresh_on_delete_clears_value.flow-meta.xml
- package.json
- rollup-namespaced/README.md
- rollup-namespaced/sfdx-project.json
- rollup/core/classes/RollupCalcItemReplacer.cls
- rollup/core/classes/RollupLogger.cls
- scripts/convert-dlrs-rules-namespaced.apex
- scripts/convert-dlrs-rules.apex
- sfdx-project.json
* Fixed several test issues that were preventing namespace package generation
* Finished optimization work that's been going on for several releases now on `RollupCalcItemReplacer`
* Updated the namespaced package migration script for DLRS to properly refer to the namespaced package's Rollup Control record
> v1.5.80 - Namespace Package Updates

- README.md
- extra-tests/classes/RollupCalculatorTests.cls
- package.json
- rollup-namespaced/README.md
- rollup-namespaced/sfdx-project.json
- rollup/app/permissionsets/See_Rollup_App.permissionset-meta.xml
- rollup/app/permissionsets/See_Rollup_Button.permissionset-meta.xml
- rollup/core/classes/RollupAsyncProcessor.cls
- rollup/core/classes/RollupCalculator.cls
- rollup/core/classes/RollupFullRecalcProcessor.cls
- rollup/core/classes/RollupLogger.cls
- sfdx-project.json
* A bit of cleanup following #503
> v1.5.87 - Housekeeping

- README.md
- extra-tests/classes/RollupIntegrationTests.cls
- extra-tests/classes/RollupRepositoryTests.cls
- package.json
- rollup-namespaced/README.md
- rollup-namespaced/sfdx-project.json
- rollup/core/classes/Rollup.cls
- rollup/core/classes/RollupAsyncProcessor.cls
- rollup/core/classes/RollupFullRecalcProcessor.cls
- rollup/core/classes/RollupLogger.cls
- rollup/core/classes/RollupMetaPicklists.cls
- rollup/core/classes/RollupRepository.cls
- sfdx-project.json
* Fixes an issue discussed in #532 (and possibly #533) that was affecting some scheduled runs of Apex Rollup due to a serialization issue with the newer `System.AccessLevel` enum
* Added a test proving that #537 already works
> v1.6.4 - Scheduled Flow/Job bugfix

- README.md
- package.json
- rollup-namespaced/README.md
- rollup-namespaced/sfdx-project.json
- rollup/core/classes/Rollup.cls
- rollup/core/classes/RollupCalcItemReplacer.cls
- rollup/core/classes/RollupEvaluator.cls
- rollup/core/classes/RollupLogger.cls
- rollup/core/classes/RollupRecursionItem.cls
- sfdx-project.json
* fixes #539 by optimizing the update code path for rollups started by Flow
> v1.6.5 - Flow Optimizations

- scripts/test.sh
This command did not migrate when moving from sfdx to sf commands
> fix: update sf cli list limits command

- README.md
- extra-tests/classes/RollupFullRecalcTests.cls
- package.json
- plugins/CustomObjectRollupLogger/tests/RollupCustomObjectLoggerTests.cls
- rollup-namespaced/README.md
- rollup-namespaced/sfdx-project.json
- rollup/core/classes/Rollup.cls
- rollup/core/classes/RollupAsyncProcessor.cls
- rollup/core/classes/RollupFullRecalcProcessor.cls
- rollup/core/classes/RollupLogger.cls
- rollup/core/classes/RollupParentResetProcessor.cls
- scripts/generatePackage.ps1
- sfdx-project.json
* Continuation from #540 with more flow improvements. This is another big update to the efficiency of Apex Rollup when invoked from Flow, particularly for bulk updates
* Fixed an issue reported by Katherine West where logging wasn't re-disabled after outputting the "starting to timeout..." log message
* Adding scopeProfiles property to sfdx-project.json care of @jefersonchaves
> v1.6.11 - Continued Flow Optimizations

- Contributing.md
* Adds instructions on installing the Nebula Logger Core dependency.
* Adds instructions on assigning permission sets to access the app in the development environment.
> Adds more detailed instructions for contributing

- README.md
- package.json
- rollup-namespaced/README.md
- rollup-namespaced/sfdx-project.json
- rollup/core/classes/RollupLogger.cls
- sfdx-project.json
* Allows namespaced package subscribers to properly extend/implement `RollupLogger` interfaces for logging plugins
> v1.6.24 - Update RollupLogger interface visibility

- .forceignore
- .github/workflows/deploy.yml
- README.md
- extra-tests/classes/RollupEvaluatorTests.cls
- package.json
- rollup-namespaced/README.md
- rollup-namespaced/sfdx-project.json
- rollup/core/classes/RollupEvaluator.cls
- rollup/core/classes/RollupLogger.cls
- scripts/updateGithubCommitStatus.sh
- sfdx-project.json
* [Updates pipeline to only run SF scanner for dependabot PRs](https://github.com/jamessimone/apex-rollup/commit/bbefea35a3f3b7f150896fc7386a52ceddfa4e16)
* [Fixes issue discussed in](https://github.com/jamessimone/apex-rollup/commit/42e28b301e4ca614baf8b9ad9c9035feb05d333d) https://github.com/jamessimone/apex-rollup/discussions/562 [where sync rollups using lowercase relationship queries in where clauses would not start up properly](https://github.com/jamessimone/apex-rollup/commit/42e28b301e4ca614baf8b9ad9c9035feb05d333d)
> v1.6.31 - Allow Lowercase Field Names For Sync Rollups

- README.md
- extra-tests/classes/RollupCalcItemReplacerTests.cls
- package.json
- rollup-namespaced/README.md
- rollup-namespaced/sfdx-project.json
- rollup/core/classes/RollupAsyncProcessor.cls
- rollup/core/classes/RollupCalcItemReplacer.cls
- rollup/core/classes/RollupLogger.cls
- sfdx-project.json
* Fixes #688 by properly handling non-polymorphic Type fields used in parent where clauses
> v1.7.17 - Non-Polymorphic Type Where Clause Bugfix

- README.md
- extra-tests/classes/RollupTests.cls
- package.json
- plugins/ExtraCodeCoverage/README.md
- rollup-namespaced/README.md
- rollup-namespaced/sfdx-project.json
- rollup/core/classes/RollupAsyncProcessor.cls
- rollup/core/classes/RollupFinalizer.cls
- rollup/core/classes/RollupLogger.cls
- rollup/core/classes/RollupRepository.cls
- rollup/core/objects/Rollup__mdt/fields/UltimateParentLookupText__c.field-meta.xml
- sfdx-project.json
* Trims down fields queried in `RollupRepository` for rollup metadata
* Adds additional logging in `RollupAsyncProcessor` when no matching rollups are found
* Adds additional logging to start/finish for `RollupFinalizer`
* Generated new Extra Tests plugin package
> v1.7.22 - Cleanup

- README.md
- package.json
- rollup-namespaced/README.md
- rollup-namespaced/sfdx-project.json
- rollup/core/classes/RollupFlowFullRecalcDispatcher.cls
- rollup/core/classes/RollupFlowRecalculator.cls
- rollup/core/classes/RollupLogger.cls
- sfdx-project.json
Both flow full recalc invocables were still using public visibility, and some ISVs need access to those methods within their own packages - this update allows them to.
> v1.7.23 - Updates Flow full recalc actions to global visibility

- README.md
- package.json
- rollup-namespaced/README.md
- rollup-namespaced/sfdx-project.json
- rollup/core/classes/RollupDateLiteral.cls
- rollup/core/classes/RollupLogger.cls
- sfdx-project.json
Fixes an issue reported by internal colleague with `RollupDateLiteral` failing to compile when an org does not have all fiscal info set up
> v1.7.28 - Compilation Error Bugfix
